Repository mealie-recipes/mealie, pull requests merged in 2024-09, with the labels that each got.

#4147 feat: Automate release drafting
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  renovate.json
Labels: chore

#4145 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/el-GR.json
Labels: l10n

#4154 chore: Set 'chore' label on PR
  .github/workflows/scheduled-checks.yml
Labels: chore

#4153 chore: Set "documentation" label on PR
  .github/workflows/release.yml
Labels: chore

#4165 docs: OpenAI Documentation
  docs/docs/documentation/getting-started/installation/backend-config.md
  docs/docs/documentation/getting-started/installation/open-ai.md
Labels: documentation

#4167 docs: Added OpenAI Page to mkdocs
  docs/mkdocs.yml
Labels: documentation

#4116 docs: add keep screen alive entry
  docs/docs/documentation/getting-started/faq.md
Labels: documentation

#4111 feat: Added feature to limit mealplan data by date range
  mealie/repos/repository_meals.py
  mealie/services/event_bus_service/event_bus_listeners.py
  tests/unit_tests/services_tests/scheduler/tasks/test_post_webhook.py
Labels: breaking-change

#4171 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/units/locales/fr-FR.json
Labels: l10n

#4176 chore(l10n): New Crowdin updates
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/es-ES.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/units/locales/da-DK.json
Labels: l10n

#4181 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/fr-CA.json
  mealie/lang/messages/fr-CA.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/fr-CA.json
  mealie/repos/seed/resources/labels/locales/fr-CA.json
  mealie/repos/seed/resources/units/locales/fr-CA.json
Labels: l10n

#4188 feat: Add autolabeler functionality for PRs
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#4196 feat: Change autolabeler regex to include :
  .github/release-drafter.yml
Labels: feature

#4130 docs: boolean value in docker-compose examples not deserializable in env variables
  docs/docs/documentation/getting-started/installation/postgres.md
  docs/docs/documentation/getting-started/installation/sqlite.md
Labels: documentation

#4150 fix: Tweak recipe card height to be consistent
  frontend/components/Domain/Recipe/RecipeCardMobile.vue
  frontend/components/Domain/Recipe/RecipeCardSection.vue
Labels: bugfix

#4183 fix: Broken Social Preview Links
  mealie/routes/spa/__init__.py
  tests/integration_tests/test_spa.py
Labels: bugfix

#4200 feat: Reorder ShoppingListItemEditor
  frontend/components/Domain/ShoppingList/ShoppingListItemEditor.vue
Labels: feature

#4163 feat: Use Backend for Recipe Post Actions
  docs/docs/documentation/getting-started/features.md
  frontend/components/Domain/Recipe/RecipeContextMenu.vue
  frontend/composables/use-group-recipe-actions.ts
  frontend/lib/api/types/household.ts
  frontend/lib/api/user/group-recipe-actions.ts
  mealie/routes/households/controller_group_recipe_actions.py
  mealie/schema/household/__init__.py
  mealie/schema/household/group_recipe_action.py
  tests/integration_tests/user_household_tests/test_group_recipe_actions.py
  tests/utils/api_routes/__init__.py
Labels: feature, breaking-change

#4204 fix(deps): Update dependencies for Python 3.12
  poetry.lock
Labels: chore

#4186 feat: Allow Cookbooks To Share Names
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/Layout/LayoutParts/AppSidebar.vue
  frontend/types/application-types.ts
  mealie/repos/repository_cookbooks.py
  mealie/repos/repository_factory.py
  mealie/schema/cookbook/cookbook.py
  tests/integration_tests/public_explorer_tests/test_public_cookbooks.py
  tests/unit_tests/repository_tests/test_cookbook_repository.py
Labels: feature

#4192 chore: Improve Alembic Migration Generation
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/2022-02-21-19.56.24_6b0f5f32d602_initial_tables.py
  alembic/versions/2022-03-23-17.43.34_263dd6707191_convert_quantity_from_integer_to_float.py
  alembic/versions/2022-03-27-19.30.28_f1a2dbee5fe9_add_original_text_column_to_recipes_.py
  alembic/versions/2022-03-31-19.19.55_59eb59135381_add_tags_to_cookbooks.py
  alembic/versions/2022-04-03-10.48.51_09dfc897ad62_add_require_all_for_cookbook_filters.py
  alembic/versions/2022-06-01-11.12.06_ab0bae02578f_add_use_abbreviation_column_to_.py
  alembic/versions/2022-06-15-21.05.34_f30cf048c228_add_new_webhook_fields.py
  alembic/versions/2022-08-12-19.05.59_188374910655_add_login_attemps_and_locked_at_field_.py
  alembic/versions/2022-08-13-17.07.07_089bfa50d0ed_add_is_ocr_recipe_column_to_recipes.py
  alembic/versions/2022-08-29-13.57.40_44e8d670719d_add_extras_to_shopping_lists_list_items_.py
  alembic/versions/2022-09-27-14.53.14_2ea7a807915c_add_recipe_timeline_events_table.py
  alembic/versions/2022-11-03-13.10.24_1923519381ad_renamed_timeline_event_message_and_.py
  alembic/versions/2022-11-22-03.42.45_167eb69066ad_add_recipe_scale_to_shopping_list_item_.py
  alembic/versions/2023-01-21-16.54.44_165d943c64ee_add_related_user_to_mealplan.py
  alembic/versions/2023-02-07-20.57.21_ff5f73b01a7a_add_missing_foreign_key_and_order_.py
  alembic/versions/2023-02-10-21.18.32_16160bf731a0_add_more_indices_necessary_for_search.py
  alembic/versions/2023-02-14-20.45.41_5ab195a474eb_add_normalized_search_properties.py
  alembic/versions/2023-02-21-22.03.19_b04a08da2108_added_shopping_list_label_settings.py
  alembic/versions/2023-02-22-21.45.52_38514b39a824_add_auth_method_to_user_table.py
  alembic/versions/2023-04-13-06.47.04_b3dbb554ba53_postgres_fuzzy_search.py
  alembic/versions/2023-08-06-21.00.34_04ac51cbe9a4_added_group_slug.py
  alembic/versions/2023-08-14-19.30.49_1825b5225403_added_recipe_note_to_shopping_list_.py
  alembic/versions/2023-08-15-16.25.07_bcfdad6b7355_remove_tool_name_and_slug_unique_.py
  alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
  alembic/versions/2023-10-04-14.29.26_dded3119c1fe_added_unique_constraints.py
  alembic/versions/2023-10-19-19.22.55_ba1e4a6cfe99_added_plural_names_and_alias_tables_for_.py
  alembic/versions/2024-02-23-16.15.07_2298bb460ffd_added_user_to_shopping_list.py
  alembic/versions/2024-03-10-05.08.32_09aba125b57a_add_oidc_auth_method.py
  alembic/versions/2024-03-18-02.28.15_d7c6efd2de42_migrate_favorites_and_ratings_to_user_.py
  alembic/versions/2024-04-07-01.05.20_7788478a0338_add_group_recipe_actions.py
  alembic/versions/2024-06-22-10.17.03_32d69327997b_add_staple_flag_to_foods.py
  alembic/versions/2024-07-12-16.16.29_feecc8ffb956_add_households.py
  docs/docs/contributors/developers-guide/database-changes.md
Labels: chore

#4158 feat: Additional Household Permissions
  alembic/versions/2024-09-02-21.39.49_be568e39ffdf_added_household_recipe_lock_setting_and_.py
  frontend/components/Domain/Household/HouseholdPreferencesEditor.vue
  frontend/components/Domain/Recipe/RecipeCard.vue
  frontend/components/Domain/Recipe/RecipeCardMobile.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageHeader.vue
  frontend/composables/recipes/use-recipe-permissions.test.ts
  frontend/composables/recipes/use-recipe-permissions.ts
  frontend/composables/use-households.ts
  frontend/composables/use-users/user-form.ts
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/admin.ts
  frontend/lib/api/types/household.ts
  frontend/lib/api/types/openai.ts
  frontend/lib/api/types/user.ts
  frontend/lib/api/user/groups.ts
  frontend/middleware/can-manage-household-only.ts
  frontend/pages/admin/manage/households/_id.vue
  frontend/pages/household/index.vue
  frontend/pages/household/members.vue
  frontend/pages/user/profile/index.vue
  mealie/db/models/household/preferences.py
  mealie/db/models/users/users.py
  mealie/routes/_base/checks.py
  mealie/routes/groups/controller_group_self_service.py
  mealie/routes/households/controller_household_self_service.py
  mealie/schema/household/household_permissions.py
  mealie/schema/household/household_preferences.py
  mealie/schema/openai/__init__.py
  mealie/schema/user/user.py
  mealie/services/recipe/recipe_service.py
  mealie/services/user_services/registration_service.py
  tests/integration_tests/admin_tests/test_admin_household_actions.py
  tests/integration_tests/user_group_tests/test_group_self_service.py
  tests/integration_tests/user_household_tests/test_household_perferences.py
  tests/integration_tests/user_household_tests/test_household_permissions.py
  tests/integration_tests/user_recipe_tests/test_recipe_cross_household.py
  tests/utils/api_routes/__init__.py
Labels: feature

#4230 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/units/locales/sv-SE.json
Labels: l10n

#4233 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/sv-SE.json
Labels: l10n

#4237 feat: Shopping list UI overhaul - increase list item width
  frontend/components/Domain/ShoppingList/ShoppingListItem.vue
Labels: feature

#4238 feat: Shopping list UI overhaul - label sorted by default
  frontend/composables/use-users/preferences.ts
Labels: feature

#4220 chore: Optimize Loads on Queries
  mealie/repos/repository_recipes.py
  mealie/schema/household/group_shopping_list.py
  mealie/schema/household/household_preferences.py
  mealie/schema/meal_plan/new_meal.py
  mealie/schema/recipe/recipe.py
  mealie/schema/recipe/recipe_timeline_events.py
  mealie/schema/user/user.py
Labels: chore

#4241 fix: revert shopping list items - increased width
  frontend/components/Domain/ShoppingList/ShoppingListItem.vue
Labels: bugfix

#4218 fix: Exclude additional sensitive information from mealie logs
  mealie/app.py
Labels: bugfix

#4227 feat: OpenAI Custom Headers/Params and Debug Page
  docs/docs/documentation/getting-started/installation/backend-config.md
  docs/docs/overrides/api.html
  frontend/components/Layout/LayoutParts/AppSidebar.vue
  frontend/lang/messages/en-US.json
  frontend/layouts/admin.vue
  frontend/lib/api/admin/admin-debug.ts
  frontend/lib/api/client-admin.ts
  frontend/lib/api/types/admin.ts
  frontend/pages/admin/debug/openai.vue
  frontend/pages/admin/debug/parser.vue
  mealie/core/settings/settings.py
  mealie/routes/admin/__init__.py
  mealie/routes/admin/admin_debug.py
  mealie/schema/admin/__init__.py
  mealie/schema/admin/debug.py
  mealie/services/openai/openai.py
  mealie/services/openai/prompts/debug.txt
  mealie/services/parser_services/openai/parser.py
  mealie/services/recipe/recipe_service.py
  tests/utils/api_routes/__init__.py
Labels: feature

#4256 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
Labels: l10n

#4264 chore(l10n): New Crowdin updates
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/uk-UA.json
  mealie/repos/seed/resources/units/locales/hu-HU.json
  mealie/repos/seed/resources/units/locales/uk-UA.json
Labels: l10n

#4235 feat: Shopping list UI overhaul - add label headings per category
  frontend/pages/group/data/labels.vue
  frontend/pages/shopping-lists/_id.vue
  mealie/schema/labels/multi_purpose_label.py
Labels: feature

#4253 feat: sort labels by name,asc in shopping lists
  frontend/pages/shopping-lists/_id.vue
Labels: feature

#4268 chore(l10n): New Crowdin updates
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sv-SE.json
Labels: l10n

#4266 docs: Update Docs for Households
  docs/docs/contributors/developers-guide/migration-guide.md
  docs/docs/documentation/getting-started/faq.md
  docs/docs/documentation/getting-started/features.md
  docs/docs/documentation/getting-started/introduction.md
  docs/docs/documentation/getting-started/updating.md
  docs/docs/documentation/getting-started/usage/permissions-and-public-access.md
  docs/docs/overrides/api.html
  docs/mkdocs.yml
Labels: documentation

#4271 chore(l10n): New Crowdin updates
  frontend/lang/messages/ru-RU.json
  mealie/repos/seed/resources/units/locales/ru-RU.json
Labels: l10n

#4174 feat: add regex to url before scraping
  mealie/services/scraper/scraper.py
Labels: feature

#4231 feat: Add Household Filter to Meal Plan Rules
  alembic/versions/2024-09-18-14.52.55_1fe4bd37ccc8_add_households_filter_to_meal_plans.py
  frontend/components/Domain/Household/GroupHouseholdSelector.vue
  frontend/components/Domain/Household/GroupMealPlanRuleForm.vue
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/meal-plan.ts
  frontend/pages/household/mealplan/settings.vue
  mealie/db/models/household/mealplan.py
  mealie/repos/repository_generic.py
  mealie/repos/repository_recipes.py
  mealie/routes/households/controller_mealplan.py
  mealie/schema/meal_plan/__init__.py
  mealie/schema/meal_plan/plan_rules.py
  tests/integration_tests/user_household_tests/test_group_mealplan.py
Labels: feature

#4280 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
Labels: l10n

#4278 fix: Hide rating on notes
  frontend/components/Domain/Recipe/RecipeCardMobile.vue
Labels: bugfix

#4236 feat: Shopping list UI overhaul - add wakelock
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/global/WakelockSwitch.vue
  frontend/pages/shopping-lists/_id.vue
Labels: feature

#4289 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/el-GR.json
Labels: l10n

#4287 docs: add note on recipe scaling to docs
  docs/docs/documentation/getting-started/faq.md
  docs/docs/overrides/api.html
Labels: documentation

#4274 feat: Create Recipe From HTML or JSON
  docs/docs/contributors/developers-guide/migration-guide.md
  docs/docs/documentation/community-guide/bulk-url-import.md
  docs/docs/documentation/getting-started/installation/security.md
  frontend/components/global/RecipeJsonEditor.vue
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/recipe.ts
  frontend/lib/api/user/recipes/recipe.ts
  frontend/lib/icons/icons.ts
  frontend/pages/g/_groupSlug/r/create.vue
  frontend/pages/g/_groupSlug/r/create/html.vue
  frontend/pages/g/_groupSlug/r/create/url.vue
  frontend/pages/g/_groupSlug/r/create/zip.vue
  mealie/routes/recipe/recipe_crud_routes.py
  mealie/schema/recipe/__init__.py
  mealie/schema/recipe/recipe_scraper.py
  mealie/services/scraper/recipe_bulk_scraper.py
  mealie/services/scraper/recipe_scraper.py
  mealie/services/scraper/scraper.py
  mealie/services/scraper/scraper_strategies.py
  tests/integration_tests/user_recipe_tests/test_recipe_create_from_image.py
  tests/integration_tests/user_recipe_tests/test_recipe_crud.py
  tests/unit_tests/test_recipe_parser.py
  tests/utils/api_routes/__init__.py
Labels: feature, breaking-change

#4292 fix: add setting to fix mypy pydantic warning on vs code dev container setup
  .devcontainer/devcontainer.json
Labels: bugfix

#4293 fix: scrape images as list
  mealie/services/scraper/scraper.py
Labels: bugfix
