Repository mealie-recipes/mealie, pull requests merged in 2024-12, with the labels that each got.

#4654 docs: Update authelia link in oidc.md
  docs/docs/documentation/getting-started/authentication/oidc.md
Labels: documentation

#4653 fix: Improve UX for new households/userrs
  frontend/lang/messages/en-US.json
  frontend/pages/admin/manage/households/index.vue
  frontend/pages/admin/manage/users/create.vue
Labels: bugfix

#4542 feat: Recipe Finder (aka Cocktail Builder)
  frontend/assets/css/main.css
  frontend/components/Domain/QueryFilterBuilder.vue
  frontend/components/Domain/Recipe/RecipeSuggestion.vue
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/global/BaseDialog.vue
  frontend/composables/use-users/preferences.ts
  frontend/lang/messages/en-US.json
  frontend/lib/api/public/explore/recipes.ts
  frontend/lib/api/types/recipe.ts
  frontend/lib/api/types/response.ts
  frontend/lib/api/user/recipes/recipe.ts
  frontend/pages/g/_groupSlug/recipes/finder/index.vue
  mealie/repos/repository_generic.py
  mealie/repos/repository_recipes.py
  mealie/routes/explore/controller_public_recipes.py
  mealie/routes/recipe/__init__.py
  mealie/routes/recipe/_base.py
  mealie/routes/recipe/exports.py
  mealie/routes/recipe/recipe_crud_routes.py
  mealie/routes/recipe/timeline_events.py
  mealie/schema/recipe/__init__.py
  mealie/schema/recipe/recipe_suggestion.py
  mealie/schema/response/__init__.py
  mealie/schema/response/pagination.py
  tests/integration_tests/public_explorer_tests/test_public_recipes.py
  tests/integration_tests/user_recipe_tests/test_recipe_suggestions.py
  tests/unit_tests/repository_tests/test_pagination.py
  tests/utils/api_routes/__init__.py
Labels: feature

#4672 fix: Cocktail Builder Enhancements
  frontend/pages/g/_groupSlug/recipes/finder/index.vue
Labels: bugfix

#4615 fix: Meal Plan Notes allow Submission Without Title/Note Text
  frontend/pages/household/mealplan/planner/edit.vue
Labels: bugfix

#4329 feat: Move alembic config into mealie package for easier distribution
  Taskfile.yml
  docker/Dockerfile
  mealie/alembic/README
  mealie/alembic/alembic.ini
  mealie/alembic/env.py
  mealie/alembic/script.py.mako
  mealie/alembic/versions/2022-02-21-19.56.24_6b0f5f32d602_initial_tables.py
  mealie/alembic/versions/2022-03-23-17.43.34_263dd6707191_convert_quantity_from_integer_to_float.py
  mealie/alembic/versions/2022-03-27-19.30.28_f1a2dbee5fe9_add_original_text_column_to_recipes_.py
  mealie/alembic/versions/2022-03-31-19.19.55_59eb59135381_add_tags_to_cookbooks.py
  mealie/alembic/versions/2022-04-03-10.48.51_09dfc897ad62_add_require_all_for_cookbook_filters.py
  mealie/alembic/versions/2022-06-01-11.12.06_ab0bae02578f_add_use_abbreviation_column_to_.py
  mealie/alembic/versions/2022-06-15-21.05.34_f30cf048c228_add_new_webhook_fields.py
  mealie/alembic/versions/2022-08-12-19.05.59_188374910655_add_login_attemps_and_locked_at_field_.py
  mealie/alembic/versions/2022-08-13-17.07.07_089bfa50d0ed_add_is_ocr_recipe_column_to_recipes.py
  mealie/alembic/versions/2022-08-29-13.57.40_44e8d670719d_add_extras_to_shopping_lists_list_items_.py
  mealie/alembic/versions/2022-09-27-14.53.14_2ea7a807915c_add_recipe_timeline_events_table.py
  mealie/alembic/versions/2022-11-03-13.10.24_1923519381ad_renamed_timeline_event_message_and_.py
  mealie/alembic/versions/2022-11-22-03.42.45_167eb69066ad_add_recipe_scale_to_shopping_list_item_.py
  mealie/alembic/versions/2023-01-21-16.54.44_165d943c64ee_add_related_user_to_mealplan.py
  mealie/alembic/versions/2023-02-07-20.57.21_ff5f73b01a7a_add_missing_foreign_key_and_order_.py
  mealie/alembic/versions/2023-02-10-21.18.32_16160bf731a0_add_more_indices_necessary_for_search.py
  mealie/alembic/versions/2023-02-14-20.45.41_5ab195a474eb_add_normalized_search_properties.py
  mealie/alembic/versions/2023-02-21-22.03.19_b04a08da2108_added_shopping_list_label_settings.py
  mealie/alembic/versions/2023-02-22-21.45.52_38514b39a824_add_auth_method_to_user_table.py
  mealie/alembic/versions/2023-04-13-06.47.04_b3dbb554ba53_postgres_fuzzy_search.py
  mealie/alembic/versions/2023-08-06-21.00.34_04ac51cbe9a4_added_group_slug.py
  mealie/alembic/versions/2023-08-14-19.30.49_1825b5225403_added_recipe_note_to_shopping_list_.py
  mealie/alembic/versions/2023-08-15-16.25.07_bcfdad6b7355_remove_tool_name_and_slug_unique_.py
  mealie/alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
  mealie/alembic/versions/2023-10-04-14.29.26_dded3119c1fe_added_unique_constraints.py
  mealie/alembic/versions/2023-10-19-19.22.55_ba1e4a6cfe99_added_plural_names_and_alias_tables_for_.py
  mealie/alembic/versions/2024-02-23-16.15.07_2298bb460ffd_added_user_to_shopping_list.py
  mealie/alembic/versions/2024-03-10-05.08.32_09aba125b57a_add_oidc_auth_method.py
  mealie/alembic/versions/2024-03-18-02.28.15_d7c6efd2de42_migrate_favorites_and_ratings_to_user_.py
  mealie/alembic/versions/2024-04-07-01.05.20_7788478a0338_add_group_recipe_actions.py
  mealie/alembic/versions/2024-06-22-10.17.03_32d69327997b_add_staple_flag_to_foods.py
  mealie/alembic/versions/2024-07-12-16.16.29_feecc8ffb956_add_households.py
  mealie/alembic/versions/2024-09-02-21.39.49_be568e39ffdf_added_household_recipe_lock_setting_and_.py
  mealie/alembic/versions/2024-09-18-14.52.55_1fe4bd37ccc8_add_households_filter_to_meal_plans.py
  mealie/alembic/versions/2024-10-01-14.17.00_602927e1013e_add_the_rest_of_the_schema_org_.py
  mealie/alembic/versions/2024-10-08-21.17.31_86054b40fd06_added_query_filter_string_to_cookbook_.py
  mealie/alembic/versions/2024-10-20-09.47.46_3897397b4631_add_summary_to_recipe_instructions.py
  mealie/alembic/versions/2024-10-23-15.50.59_b1020f328e98_add_recipe_yield_quantity.py
  mealie/db/init_db.py
  mealie/services/backups_v2/alchemy_exporter.py
  pyproject.toml
  tests/utils/alembic_reader.py
Labels: feature

#4680 fix: remove import button from recipe data view
  frontend/pages/group/data/recipes.vue
Labels: bugfix

#4675 feat: Upgrade to Python 3.12
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/partial-backend.yml
  .github/workflows/scheduled-checks.yml
  docker/Dockerfile
  docs/docs/contributors/developers-guide/starting-dev-server.md
  mealie/alembic/versions/2024-03-18-02.28.15_d7c6efd2de42_migrate_favorites_and_ratings_to_user_.py
  mealie/alembic/versions/2024-07-12-16.16.29_feecc8ffb956_add_households.py
  mealie/core/release_checker.py
  mealie/core/security/providers/auth_provider.py
  mealie/core/security/security.py
  mealie/core/settings/settings.py
  mealie/db/models/_model_utils/datetime.py
  mealie/db/models/household/shopping_list.py
  mealie/db/models/household/webhooks.py
  mealie/db/models/recipe/recipe.py
  mealie/db/models/recipe/recipe_timeline.py
  mealie/db/models/recipe/shared.py
  mealie/repos/repository_generic.py
  mealie/repos/repository_meals.py
  mealie/repos/repository_recipes.py
  mealie/routes/households/controller_webhooks.py
  mealie/schema/_mealie/datetime_parse.py
  mealie/schema/_mealie/mealie_model.py
  mealie/schema/household/webhook.py
  mealie/schema/recipe/recipe_share_token.py
  mealie/schema/recipe/recipe_timeline_events.py
  mealie/schema/user/user.py
  mealie/services/backups_v2/backup_v2.py
  mealie/services/event_bus_service/event_bus_listeners.py
  mealie/services/event_bus_service/event_types.py
  mealie/services/exporter/exporter.py
  mealie/services/migrations/copymethat.py
  mealie/services/recipe/recipe_service.py
  mealie/services/scheduler/scheduler_service.py
  mealie/services/scheduler/tasks/create_timeline_events.py
  mealie/services/scheduler/tasks/post_webhooks.py
  mealie/services/scheduler/tasks/purge_group_exports.py
  mealie/services/scheduler/tasks/purge_password_reset.py
  mealie/services/scheduler/tasks/purge_registration.py
  mealie/services/user_services/user_service.py
  poetry.lock
  pyproject.toml
Labels: feature

#4661 feat: Add 'No Shopping Lists Found' message
  frontend/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue
  frontend/lang/messages/en-US.json
  frontend/pages/shopping-lists/index.vue
Labels: feature

#4631 fix: Sort Food by Label on Data Management Page
  frontend/components/global/CrudTable.vue
  frontend/pages/group/data/foods.vue
Labels: bugfix

#4704 fix: code warnings (lint)
  frontend/pages/household/mealplan/planner/edit.vue
Labels: bugfix

#4703 fix: Add Formatting for Markdown Tables
  frontend/components/global/SafeMarkdown.vue
Labels: bugfix

#4666 docs: Add October 2024 survey results
  docs/docs/news/surveys/2024-october/Question2.png
  docs/docs/news/surveys/2024-october/Question3.png
  docs/docs/news/surveys/2024-october/Question4.png
  docs/docs/news/surveys/2024-october/Question5.png
  docs/docs/news/surveys/2024-october/Question6.png
  docs/docs/news/surveys/2024-october/Question7.png
  docs/docs/news/surveys/2024-october/Question8.png
  docs/docs/news/surveys/2024-october/overview.md
  docs/docs/news/surveys/2024-october/q10.md
  docs/docs/news/surveys/2024-october/q11.md
  docs/docs/news/surveys/2024-october/q12.md
  docs/docs/news/surveys/2024-october/q13.md
  docs/docs/news/surveys/2024-october/q9.md
  docs/docs/overrides/api.html
  docs/mkdocs.yml
Labels: documentation

#4734 fix: Use configured server time when calling RepositoryMeals.get_today() method
  mealie/repos/repository_meals.py
  mealie/routes/households/controller_mealplan.py
  mealie/services/scheduler/tasks/create_timeline_events.py
Labels: bugfix

#4751 chore(l10n): New Crowdin updates
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sv-SE.json
  mealie/lang/messages/ca-ES.json
  mealie/lang/messages/el-GR.json
  mealie/lang/messages/fr-FR.json
  mealie/lang/messages/hu-HU.json
  mealie/lang/messages/ja-JP.json
  mealie/lang/messages/sl-SI.json
  mealie/lang/messages/sv-SE.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/units/locales/sv-SE.json
Labels: l10n

#4754 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  mealie/lang/messages/de-DE.json
Labels: l10n

#4759 chore(l10n): New Crowdin updates
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/es-ES.json
  mealie/lang/messages/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
Labels: l10n

#4764 chore(l10n): New Crowdin updates
  frontend/lang/messages/ca-ES.json
Labels: l10n

#4774 chore(l10n): New Crowdin updates
  frontend/lang/messages/it-IT.json
  mealie/lang/messages/it-IT.json
Labels: l10n

#4784 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
Labels: l10n

#4787 chore(l10n): New Crowdin updates
  frontend/lang/messages/nl-NL.json
  mealie/lang/messages/he-IL.json
  mealie/lang/messages/nl-NL.json
Labels: l10n

#4658 chore: Add OIDC debug logging
  mealie/core/security/providers/openid_provider.py
  tests/unit_tests/core/security/providers/test_openid_provider.py
Labels: chore

#4792 fix: SyntaxWarning for Escape Characters in String Literals
  mealie/repos/repository_cookbooks.py
  mealie/schema/response/query_search.py
Labels: bugfix

#4577 fix: 3892 missing parameter documentation
  docs/docs/documentation/getting-started/installation/postgres.md
Labels: bugfix

#4801 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  mealie/repos/seed/resources/units/locales/fr-FR.json
Labels: l10n
