Repository mealie-recipes/mealie, pull requests merged in 2024-11, with the labels that each got.

#4421 feat: vrslev/pre-commit-autoupdate archived
  .github/workflows/scheduled-checks.yml
Labels: feature

#4493 fix: Added Nutrients Suffix to the PrintView and some formatting to that
  frontend/components/Domain/Recipe/RecipePrintView.vue
Labels: bugfix

#4487 fix: Scripts Missing Repo Params
  mealie/scripts/change_password.py
  mealie/scripts/reset_locked_users.py
Labels: bugfix

#4456 feat: implement the possibility to add tls
  docs/docs/documentation/getting-started/installation/backend-config.md
  mealie/core/settings/settings.py
  mealie/main.py
Labels: feature

#4452 feat: Show Cookbooks from Other Households
  frontend/components/Domain/Cookbook/CookbookPage.vue
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/Layout/LayoutParts/AppSidebar.vue
  frontend/composables/use-group-cookbooks.ts
  frontend/composables/use-users/preferences.ts
  frontend/lang/messages/en-US.json
  frontend/pages/g/_groupSlug/cookbooks/index.vue
  frontend/types/application-types.ts
  mealie/routes/_base/mixins.py
  mealie/routes/households/controller_cookbooks.py
  mealie/routes/recipe/recipe_crud_routes.py
  tests/integration_tests/user_household_tests/test_group_cookbooks.py
  tests/integration_tests/user_recipe_tests/test_recipe_cross_household.py
Labels: feature

#4513 fix: "No Label" on Shopping List can't be toggled
  frontend/pages/shopping-lists/_id.vue
Labels: bugfix

#4500 fix: Prevent Users From Being Created With Missing Group/Household
  mealie/db/models/users/users.py
  tests/unit_tests/core/security/providers/test_openid_provider.py
  tests/unit_tests/test_security.py
Labels: bugfix

#4519 fix: JSON Mode Resets Page State
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue
Labels: bugfix

#4504 feat: adds descriptions to feature checks and add them to logs
  mealie/app.py
  mealie/core/settings/settings.py
  tests/unit_tests/test_config.py
Labels: feature

#4464 feat: Added a dedicated cookmode dialog that allows for individual scrolling
  frontend/components/Domain/Recipe/RecipeIngredients.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientToolsView.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/recipe.ts
Labels: feature

#4538 fix: Add support for HTTPS in healthcheck
  mealie/scripts/healthcheck.py
Labels: bugfix

#4534 feat: Add Ingredients to Recipe Query Filter options
  frontend/components/Domain/Cookbook/CookbookEditor.vue
  frontend/components/Domain/Household/GroupMealPlanRuleForm.vue
Labels: feature

#4252 feat: Groups/households custom invitations
  frontend/components/Domain/User/UserInviteDialog.vue
  frontend/components/global/AppButtonCopy.vue
  frontend/lang/messages/en-US.json
  frontend/pages/admin/manage/users/index.vue
  frontend/pages/user/profile/index.vue
  mealie/routes/households/controller_invitations.py
  mealie/schema/household/invite_token.py
  tests/integration_tests/user_household_tests/test_group_invitation.py
Labels: feature

#4539 fix: Cookmode hide additional ingredients if all ingredients are linked
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue
Labels: bugfix

#4554 fix: Wakelock Toggle Broken
  frontend/components/global/WakelockSwitch.vue
Labels: bugfix

#4546 fix: Update Firefox User-Agent string
  mealie/services/recipe/recipe_data_service.py
  mealie/services/scraper/scraper_strategies.py
Labels: bugfix

#4568 fix: container name for account unlock and password reset
  docs/docs/documentation/getting-started/faq.md
  docs/docs/overrides/api.html
Labels: bugfix

#4550 docs: Update docker compose examples
  docs/docs/documentation/getting-started/installation/postgres.md
  docs/docs/documentation/getting-started/installation/sqlite.md
Labels: documentation

#4562 fix: 4497
  mealie/lang/messages/en-US.json
  mealie/services/recipe/recipe_service.py
Labels: bugfix

#4602 chore(deps): Bump Ruff
  mealie/db/models/household/shopping_list.py
  poetry.lock
  pyproject.toml
Labels: chore

#4590 dev: Fix json2ts codegen
  dev/code-generation/gen_ts_types.py
  frontend/lib/api/types/admin.ts
  frontend/lib/api/types/cookbook.ts
  frontend/lib/api/types/household.ts
  frontend/lib/api/types/meal-plan.ts
  frontend/lib/api/types/openai.ts
  frontend/lib/api/types/recipe.ts
  frontend/lib/api/types/reports.ts
  frontend/lib/api/types/response.ts
  frontend/lib/api/types/user.ts
Labels: dev

#4605 fix: Incorrect date format in Add to mealplan modal
  frontend/components/Domain/Recipe/RecipeContextMenu.vue
Labels: bugfix

#4614 docs: Update API path in home-assistant.md
  docs/docs/documentation/community-guide/home-assistant.md
Labels: documentation
