Repository mealie-recipes/mealie, pull requests merged in 2024-10, with the labels that each got.

#4298 feat: refactor recipe scaling
  docs/docs/documentation/getting-started/faq.md
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageScale.vue
  frontend/components/Domain/Recipe/RecipeScaleEditButton.vue
  frontend/composables/recipe-page/use-extract-recipe-yield.ts
  frontend/lang/messages/en-US.json
Labels: feature

#4300 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/labels/locales/ro-RO.json
Labels: l10n

#4302 fix: Shopping List Label Text Color
  frontend/components/Domain/ShoppingList/MultiPurposeLabel.vue
  frontend/composables/use-text-color.ts
  frontend/pages/shopping-lists/_id.vue
Labels: bugfix

#4306 fix: GH Actions node deprecation
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/partial-backend.yml
  .github/workflows/partial-frontend.yml
  .github/workflows/partial-trivy-container-scanning.yml
Labels: bugfix

#4308 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
Labels: l10n

#4309 docs: Fix Formatting
  docs/docs/contributors/developers-guide/migration-guide.md
  docs/docs/documentation/getting-started/updating.md
  docs/docs/overrides/api.html
Labels: documentation

#4254 feat: Add OIDC_CLIENT_SECRET and other changes for v2
  docker/docker-compose.yml
  docs/docs/documentation/getting-started/authentication/oidc-v2.md
  docs/docs/documentation/getting-started/installation/backend-config.md
  docs/docs/overrides/api.html
  docs/mkdocs.yml
  frontend/components/Layout/LayoutParts/AppHeader.vue
  frontend/lib/api/types/admin.ts
  frontend/lib/api/types/user.ts
  frontend/nuxt.config.js
  frontend/pages/login.vue
  frontend/schemes/DynamicOpenIDConnectScheme.js
  mealie/app.py
  mealie/core/security/providers/auth_provider.py
  mealie/core/security/providers/credentials_provider.py
  mealie/core/security/providers/ldap_provider.py
  mealie/core/security/providers/openid_provider.py
  mealie/core/security/security.py
  mealie/core/settings/settings.py
  mealie/routes/app/app_about.py
  mealie/routes/auth/auth.py
  mealie/schema/admin/__init__.py
  mealie/schema/admin/about.py
  mealie/schema/user/__init__.py
  mealie/schema/user/auth.py
  poetry.lock
  pyproject.toml
  tests/e2e/docker/docker-compose.yml
  tests/e2e/yarn.lock
  tests/unit_tests/core/security/providers/test_openid_provider.py
  tests/unit_tests/test_security.py
  tests/utils/api_routes/__init__.py
Labels: feature, breaking-change

#4317 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/units/locales/pl-PL.json
  mealie/repos/seed/resources/units/locales/pt-BR.json
Labels: l10n

#4310 fix: Strip Timezone from Timestamps in DB
  mealie/db/migration_types.py
  mealie/db/models/_model_base.py
  mealie/db/models/_model_utils/datetime.py
  mealie/db/models/group/report.py
  mealie/db/models/recipe/recipe.py
  mealie/db/models/recipe/recipe_timeline.py
  mealie/db/models/recipe/shared.py
  mealie/db/models/server/task.py
  mealie/db/models/users/users.py
  mealie/schema/response/query_filter.py
  mealie/services/scheduler/tasks/purge_group_exports.py
Labels: bugfix

#4324 fix: recipe scaling
  frontend/components/Domain/Recipe/RecipeScaleEditButton.vue
Labels: bugfix

#4305 feat: Added support for plural_name for foods
  mealie/repos/seed/resources/foods/locales/af-ZA.json
  mealie/repos/seed/resources/foods/locales/ar-SA.json
  mealie/repos/seed/resources/foods/locales/bg-BG.json
  mealie/repos/seed/resources/foods/locales/ca-ES.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/en-US.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fi-FI.json
  mealie/repos/seed/resources/foods/locales/fr-BE.json
  mealie/repos/seed/resources/foods/locales/fr-CA.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/hr-HR.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/is-IS.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
  mealie/repos/seed/resources/foods/locales/ko-KR.json
  mealie/repos/seed/resources/foods/locales/lt-LT.json
  mealie/repos/seed/resources/foods/locales/lv-LV.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/foods/locales/pt-PT.json
  mealie/repos/seed/resources/foods/locales/ro-RO.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
  mealie/repos/seed/resources/foods/locales/sl-SI.json
  mealie/repos/seed/resources/foods/locales/sr-SP.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/foods/locales/tr-TR.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
  mealie/repos/seed/resources/foods/locales/vi-VN.json
  mealie/repos/seed/resources/foods/locales/zh-CN.json
  mealie/repos/seed/resources/foods/locales/zh-TW.json
  mealie/repos/seed/seeders.py
  tests/integration_tests/user_group_tests/test_group_seeder.py
Labels: feature

#4337 fix: user creation without username or fullName
  docs/docs/overrides/api.html
  mealie/schema/user/user.py
Labels: bugfix

#4339 chore: cancel running pull request jobs on new push
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/pull-requests.yml
Labels: chore

#4342 fix: Fix Locked User Reset
  mealie/services/scheduler/tasks/reset_locked_users.py
Labels: bugfix

#4341 docs: Update rest call for home assistant
  docs/docs/documentation/community-guide/home-assistant.md
Labels: documentation

#4347 docs: update oidc-v2.md
  docs/docs/documentation/getting-started/authentication/oidc-v2.md
Labels: documentation

#4344 chore(l10n): New Crowdin updates
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  mealie/lang/messages/fr-BE.json
  mealie/repos/seed/resources/foods/locales/af-ZA.json
  mealie/repos/seed/resources/foods/locales/ar-SA.json
  mealie/repos/seed/resources/foods/locales/bg-BG.json
  mealie/repos/seed/resources/foods/locales/ca-ES.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fi-FI.json
  mealie/repos/seed/resources/foods/locales/fr-BE.json
  mealie/repos/seed/resources/foods/locales/fr-CA.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/hr-HR.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/is-IS.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
  mealie/repos/seed/resources/foods/locales/ko-KR.json
  mealie/repos/seed/resources/foods/locales/lt-LT.json
  mealie/repos/seed/resources/foods/locales/lv-LV.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/foods/locales/pt-PT.json
  mealie/repos/seed/resources/foods/locales/ro-RO.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
  mealie/repos/seed/resources/foods/locales/sl-SI.json
  mealie/repos/seed/resources/foods/locales/sr-SP.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/foods/locales/tr-TR.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
  mealie/repos/seed/resources/foods/locales/vi-VN.json
  mealie/repos/seed/resources/foods/locales/zh-CN.json
  mealie/repos/seed/resources/foods/locales/zh-TW.json
  mealie/repos/seed/resources/units/locales/el-GR.json
  mealie/repos/seed/resources/units/locales/fr-BE.json
Labels: l10n, do not merge

#4328 fix: More Fault Tolerance with OpenAI Schemas
  mealie/schema/openai/recipe_ingredient.py
Labels: bugfix

#4319 feat: User Tooltip
  docs/docs/contributors/developers-guide/migration-guide.md
  frontend/components/Domain/Recipe/RecipeDataTable.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageComments.vue
  frontend/components/Domain/User/UserAvatar.vue
  frontend/components/Layout/LayoutParts/AppSidebar.vue
  frontend/composables/api/api-client.ts
  frontend/composables/partials/use-actions-factory.ts
  frontend/composables/partials/use-store-factory.ts
  frontend/composables/store/use-user-store.ts
  frontend/lib/api/types/user.ts
  frontend/lib/api/user/groups.ts
  frontend/lib/api/user/households.ts
  frontend/pages/household/members.vue
  frontend/pages/shopping-lists/_id.vue
  frontend/pages/user/profile/edit.vue
  frontend/pages/user/profile/index.vue
  frontend/types/components.d.ts
  mealie/routes/groups/controller_group_self_service.py
  mealie/routes/households/controller_household_self_service.py
  mealie/schema/user/user.py
  tests/integration_tests/user_group_tests/test_group_self_service.py
  tests/integration_tests/user_household_tests/test_household_self_service.py
  tests/utils/api_routes/__init__.py
Labels: feature, breaking-change

#4351 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/en-GB.json
Labels: l10n

#4356 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/en-GB.json
Labels: l10n

#4301 feat: adding the rest ofthe nutrition properties from schema.org
  alembic/versions/2024-10-01-14.17.00_602927e1013e_add_the_rest_of_the_schema_org_.py
  frontend/composables/recipes/use-recipe-nutrition.ts
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/recipe.ts
  mealie/db/models/recipe/nutrition.py
  mealie/db/models/recipe/recipe.py
  mealie/routes/spa/__init__.py
  mealie/schema/recipe/recipe_nutrition.py
  mealie/services/migrations/myrecipebox.py
  mealie/services/migrations/plantoeat.py
  mealie/services/scraper/cleaner.py
  tests/fixtures/fixture_users.py
  tests/integration_tests/recipe_migration_tests/test_recipe_migrations.py
  tests/unit_tests/services_tests/scraper_tests/test_cleaner_parts.py
  tests/unit_tests/test_recipe_parser.py
  tests/utils/recipe_data.py
Labels: feature

#4360 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
Labels: l10n

#4325 fix: Handle Data With Invalid User
  mealie/db/fixes/fix_migration_data.py
  mealie/services/backups_v2/alchemy_exporter.py
Labels: bugfix

#4364 fix: Prevent Bad Cookbook Names
  mealie/schema/cookbook/cookbook.py
  tests/integration_tests/user_household_tests/test_group_cookbooks.py
Labels: bugfix

#4371 chore(l10n): New Crowdin updates
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/ja-JP.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
  mealie/repos/seed/resources/labels/locales/de-DE.json
Labels: l10n

#4370 fix: Prevent login via credentials when Auth Method is Mealie
  docs/docs/documentation/getting-started/authentication/oidc-v2.md
  mealie/core/security/providers/credentials_provider.py
  mealie/core/security/providers/ldap_provider.py
  tests/unit_tests/core/security/providers/test_credentials_provider.py
Labels: bugfix

#4376 fix: Good data being deleted upon restore
  mealie/db/fixes/fix_migration_data.py
Labels: bugfix

#4382 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-CA.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/labels/locales/de-DE.json
  mealie/repos/seed/resources/units/locales/de-DE.json
Labels: l10n

#4379 fix: Mealplans Disappearing/Can't be edited
  frontend/pages/household/mealplan/planner/edit.vue
  mealie/schema/meal_plan/new_meal.py
Labels: bugfix

#4346 feat: Query Filter Builder for Cookbooks and Meal Plans
  alembic/versions/2024-10-08-21.17.31_86054b40fd06_added_query_filter_string_to_cookbook_.py
  frontend/components/Domain/Cookbook/CookbookEditor.vue
  frontend/components/Domain/Cookbook/CookbookPage.vue
  frontend/components/Domain/Household/GroupMealPlanRuleForm.vue
  frontend/components/Domain/QueryFilterBuilder.vue
  frontend/components/Domain/Recipe/RecipeOrganizerPage.vue
  frontend/components/Domain/Recipe/RecipeOrganizerSelector.vue
  frontend/components/global/BaseDialog.vue
  frontend/composables/partials/use-actions-factory.ts
  frontend/composables/use-group-cookbooks.ts
  frontend/composables/use-query-filter-builder.ts
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/cookbook.ts
  frontend/lib/api/types/meal-plan.ts
  frontend/lib/api/types/non-generated.ts
  frontend/lib/api/types/response.ts
  frontend/lib/api/user/group-mealplan.ts
  frontend/pages/g/_groupSlug/cookbooks/index.vue
  frontend/pages/household/mealplan/settings.vue
  mealie/db/models/household/cookbook.py
  mealie/db/models/household/mealplan.py
  mealie/db/models/labels.py
  mealie/repos/repository_generic.py
  mealie/repos/repository_recipes.py
  mealie/routes/explore/controller_public_cookbooks.py
  mealie/routes/explore/controller_public_recipes.py
  mealie/routes/households/controller_cookbooks.py
  mealie/routes/households/controller_mealplan.py
  mealie/schema/admin/__init__.py
  mealie/schema/cookbook/cookbook.py
  mealie/schema/meal_plan/__init__.py
  mealie/schema/meal_plan/plan_rules.py
  mealie/schema/response/__init__.py
  mealie/schema/response/query_filter.py
  mealie/schema/user/__init__.py
  pyproject.toml
  tests/conftest.py
  tests/integration_tests/public_explorer_tests/test_public_cookbooks.py
  tests/integration_tests/public_explorer_tests/test_public_recipes.py
  tests/integration_tests/user_household_tests/test_group_cookbooks.py
  tests/integration_tests/user_household_tests/test_group_mealplan.py
  tests/integration_tests/user_household_tests/test_group_mealplan_rules.py
  tests/integration_tests/user_recipe_tests/test_recipe_cross_household.py
  tests/integration_tests/user_recipe_tests/test_recipe_crud.py
  tests/unit_tests/repository_tests/test_query_filter_builder.py
  tests/unit_tests/services_tests/backup_v2_tests/test_backup_v2.py
  tests/utils/api_routes/__init__.py
Labels: feature, v2, breaking-change

#4389 chore(l10n): New Crowdin updates
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/tr-TR.json
  mealie/lang/messages/he-IL.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/units/locales/he-IL.json
Labels: l10n

#4355 feat: Change Recipe Owner
  frontend/components/Domain/Recipe/RecipeDataTable.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/user.ts
  frontend/lib/api/user/recipes/recipe.ts
  frontend/pages/group/data/recipes.vue
  mealie/routes/households/controller_cookbooks.py
  mealie/routes/recipe/recipe_crud_routes.py
  mealie/schema/user/user.py
  mealie/services/event_bus_service/event_types.py
  tests/integration_tests/user_recipe_tests/test_recipe_crud.py
Labels: feature

#4391 dev: Add highlights and new contributors to release template
  .github/release-drafter.yml
Labels: dev

#4393 fix: Bulk Update Owner Removes Some Recipe Data
  frontend/lib/api/user/recipes/recipe.ts
  frontend/pages/group/data/recipes.vue
  mealie/routes/recipe/recipe_crud_routes.py
  tests/integration_tests/user_recipe_tests/test_recipe_crud.py
Labels: bugfix

#4397 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/lang/messages/he-IL.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
Labels: l10n

#4405 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/he-IL.json
Labels: l10n

#4402 dev: Improve Docs Generation
  dev/code-generation/gen_docs_api.py
  docs/docs/overrides/api.html
  mealie/routes/recipe/__init__.py
  mealie/routes/recipe/bulk_actions.py
  mealie/routes/recipe/recipe_crud_routes.py
  poetry.lock
  pyproject.toml
Labels: dev

#4409 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hu-HU.json
Labels: l10n

#4414 feat: Group and household deletion tooltips
  frontend/lang/messages/en-US.json
  frontend/pages/admin/manage/groups/index.vue
  frontend/pages/admin/manage/households/index.vue
Labels: feature

#4422 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/sl-SI.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
  mealie/repos/seed/resources/units/locales/es-ES.json
Labels: l10n

#4410 feat: Add summary to recipe instructions
  alembic/versions/2024-10-20-09.47.46_3897397b4631_add_summary_to_recipe_instructions.py
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue
  frontend/components/Domain/Recipe/RecipePrintView.vue
  mealie/db/models/recipe/instruction.py
  mealie/schema/recipe/recipe_step.py
Labels: feature

#4432 chore(l10n): New Crowdin updates
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/hr-HR.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/units/locales/es-ES.json
Labels: l10n

#4434 dev: add secondary db to trivy
  .github/workflows/partial-trivy-container-scanning.yml
Labels: dev

#4429 fix: Reset Locked Users
  mealie/services/scheduler/tasks/reset_locked_users.py
  tests/unit_tests/services_tests/user_services/test_user_service.py
Labels: bugfix

#4437 fix: Add SMTP Timeout
  mealie/services/email/email_senders.py
Labels: bugfix

#4436 fix: Remove Unused Transfer Option from Shopping List
  frontend/components/Domain/ShoppingList/MultiPurposeLabelSection.vue
  frontend/components/Domain/ShoppingList/ShoppingListItem.vue
Labels: bugfix

#4440 fix: Add Touch Delay to Draggable on Touch Pads
  frontend/components/Domain/QueryFilterBuilder.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue
  frontend/pages/g/_groupSlug/cookbooks/index.vue
  frontend/pages/g/_groupSlug/r/_slug/ingredient-parser.vue
  frontend/pages/household/mealplan/planner/edit.vue
  frontend/pages/shopping-lists/_id.vue
Labels: bugfix

#4442 docs: properly set site_url for docs
  docs/mkdocs.yml
Labels: documentation

#4447 chore(l10n): New Crowdin updates
  frontend/lang/messages/sv-SE.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#4378 feat: Shopping list UI overhaul - collapsible labels
  frontend/pages/shopping-lists/_id.vue
Labels: feature

#4428 docs: Fix protocol in example URLs
  docs/docs/documentation/getting-started/authentication/oidc-v2.md
  docs/docs/documentation/getting-started/authentication/oidc.md
Labels: documentation

#4441 fix: Images Using Wrong Content Type
  docker/Dockerfile
  mealie/routes/media/media_recipe.py
  mealie/routes/media/media_user.py
Labels: bugfix

#4453 fix: Drag Delay Only Apply On Touch
  frontend/components/Domain/QueryFilterBuilder.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue
  frontend/pages/g/_groupSlug/cookbooks/index.vue
  frontend/pages/g/_groupSlug/r/_slug/ingredient-parser.vue
  frontend/pages/household/mealplan/planner/edit.vue
  frontend/pages/shopping-lists/_id.vue
Labels: bugfix

#4446 docs: Swagger/OpenAPI Organization
  docs/docs/overrides/api.html
  mealie/routes/households/controller_mealplan.py
  mealie/routes/households/controller_shopping_lists.py
  mealie/routes/organizers/controller_categories.py
  mealie/routes/parser/ingredient_parser.py
  mealie/routes/recipe/recipe_crud_routes.py
  mealie/routes/unit_and_foods/foods.py
  mealie/routes/unit_and_foods/units.py
Labels: documentation

#4450 docs: Added Missing Refs to Default Household
  Taskfile.yml
  docs/docs/documentation/getting-started/installation/backend-config.md
  docs/docs/documentation/getting-started/installation/installation-checklist.md
  tests/unit_tests/test_config.py
Labels: documentation

#4461 chore(l10n): New Crowdin updates
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/sv-SE.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#4444 fix: Disable Foreign Key Checks During Restore
  mealie/services/backups_v2/alchemy_exporter.py
  tests/data/__init__.py
  tests/data/backups/backup-version-86054b40fd06-1.zip
  tests/unit_tests/services_tests/backup_v2_tests/test_backup_v2.py
Labels: bugfix

#4435 fix: Random Recipes not choosing from all recipes
  frontend/components/Domain/Recipe/RecipeCardSection.vue
  frontend/composables/recipes/use-recipes.ts
Labels: bugfix

#4466 fix: recipe scaler throwing error on empty serving size
  frontend/components/Domain/Recipe/RecipeScaleEditButton.vue
Labels: bugfix

#4468 chore(l10n): New Crowdin updates
  frontend/lang/messages/ko-KR.json
  mealie/lang/messages/ko-KR.json
Labels: l10n

#4469 fix: set useFractions on Unit creation to true by default
  frontend/pages/group/data/units.vue
Labels: bugfix

#4470 fix: round ingredient amounts when not using fractions
  frontend/composables/recipes/use-recipe-ingredients.ts
Labels: bugfix
