Repository mealie-recipes/mealie, pull requests merged in 2025-08, with the labels that each got.

#5862 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/pt-PT.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#5867 chore(l10n): New Crowdin updates
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
Labels: l10n

#5877 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/sk-SK.json
  mealie/lang/messages/sk-SK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
Labels: l10n

#5882 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/fr-FR.json
Labels: l10n

#5884 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
Labels: l10n

#5890 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
Labels: l10n

#5894 docs: Fix broken postgres docker-compose example
  docs/docs/documentation/getting-started/installation/postgres.md
Labels: documentation

#5896 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/fr-FR.json
Labels: l10n

#5897 fix: correct JPEG media type in get_image_url to prevent API errors
  mealie/services/openai/openai.py
Labels: bugfix

#5904 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/units/locales/fr-FR.json
Labels: l10n

#5687 feat: Move create-item button in shopping list to the top
  frontend/pages/shopping-lists/[id].vue
Labels: feature

#5912 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
Labels: l10n

#5915 chore(l10n): New Crowdin updates
  frontend/lang/messages/pt-BR.json
  mealie/lang/messages/pt-BR.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
Labels: l10n

#5918 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#5716 fix: Added copy icons to first-login message
  frontend/pages/login.vue
Labels: bugfix

#5903 fix: add confidence calculation for BruteForceParser
  mealie/services/parser_services/ingredient_parser.py
  tests/unit_tests/test_ingredient_parser.py
Labels: bugfix

#5936 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
Labels: l10n

#5938 chore(l10n): New Crowdin updates
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/sv-SE.json
Labels: l10n

#5949 dev: Pin Docker Digest And Add to Renovate
  docker/Dockerfile
  renovate.json
Labels: dev

#5943 chore(l10n): New Crowdin updates
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
Labels: l10n

#5920 fix: User Registration Form Validation and Other Setup Wizard Things
  frontend/composables/use-setup/common-settings-form.ts
  frontend/composables/use-users/user-registration-form.ts
  frontend/lang/messages/en-US.json
  frontend/pages/admin/setup.vue
Labels: bugfix

#5900 fix: CONTAINS ALL doesn't contain all
  mealie/schema/response/query_filter.py
  tests/unit_tests/repository_tests/test_pagination.py
Labels: bugfix

#5964 chore(l10n): New Crowdin updates
  frontend/lang/messages/it-IT.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n

#5965 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n

#5995 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n

#6006 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-BE.json
  mealie/repos/seed/resources/foods/locales/fr-BE.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/units/locales/fr-BE.json
Labels: l10n

#6001 fix: theme dark/light are swapped
  frontend/nuxt.config.ts
  frontend/plugins/theme.ts
Labels: bugfix

#6023 fix: Remove Temperature from OpenAI Integration
  docs/docs/documentation/getting-started/installation/backend-config.md
  mealie/core/settings/settings.py
  mealie/services/openai/openai.py
Labels: bugfix

#6017 chore(l10n): New Crowdin updates
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/is-IS.json
  mealie/lang/messages/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/labels/locales/cs-CZ.json
  mealie/repos/seed/resources/units/locales/cs-CZ.json
Labels: l10n

#6014 fix: Light Mode Using Dark Mode Background Color
  frontend/plugins/theme.ts
Labels: bugfix

#6013 fix: Can't add first shopping list item to shopping list
  frontend/components/Domain/ShoppingList/ShoppingListItemEditor.vue
  frontend/components/global/InputQuantity.vue
  frontend/composables/shopping-list-page/sub-composables/use-shopping-list-crud.ts
Labels: bugfix

#6049 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
Labels: l10n

#5975 fix: re-ordering of cookbooks
  frontend/composables/store/use-cookbook-store.ts
  frontend/pages/g/[groupSlug]/cookbooks/index.vue
Labels: bugfix

#6058 chore(l10n): New Crowdin updates
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/nl-NL.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n

#6067 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n
