Repository mealie-recipes/mealie, pull requests merged in 2025-04, with the labels that each got.

#5327 fix: build pull request image only in mealie repo
  .github/workflows/pull-requests.yml
Labels: bugfix, build-image

#5345 docs: Add community docs for an iOS shortcut (attempt 2)
  docs/docs/documentation/community-guide/ios-shortcut.md
  docs/mkdocs.yml
Labels: documentation

#5360 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
Labels: l10n

#5370 chore(l10n): New Crowdin updates
  frontend/lang/messages/tr-TR.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5379 chore(l10n): New Crowdin updates
  frontend/lang/messages/sv-SE.json
Labels: l10n

#5342 fix: Add missing group_id to RecipeTag and TagBase schemas
  mealie/schema/recipe/recipe.py
  mealie/schema/recipe/recipe_category.py
  mealie/schema/recipe/recipe_tool.py
Labels: bugfix

#5390 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n

#5394 chore(l10n): New Crowdin updates
  frontend/lang/messages/ca-ES.json
Labels: l10n

#5396 chore(l10n): New Crowdin updates
  frontend/lang/messages/sk-SK.json
Labels: l10n
