Repository mealie-recipes/mealie, pull requests merged in 2025-09, with the labels that each got.

#6076 chore(l10n): New Crowdin updates
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/sk-SK.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
  mealie/repos/seed/resources/units/locales/it-IT.json
Labels: l10n

#6079 fix: Fix RecipeLastMade dialog date picker being off by a day
  frontend/components/Domain/Recipe/RecipeLastMade.vue
Labels: bugfix

#6082 docs: Fix list formatting on 'Features' docs page
  docs/docs/documentation/getting-started/features.md
Labels: documentation, feature

#6080 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  mealie/repos/seed/resources/foods/locales/ca-ES.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
  mealie/repos/seed/resources/units/locales/sk-SK.json
Labels: l10n

#6090 fix: Fix PWA
  dev/code-generation/gen_ts_locales.py
  frontend/components/Layout/DefaultLayout.vue
  frontend/i18n.config.ts
  frontend/layouts/basic.vue
  frontend/layouts/blank.vue
  frontend/nuxt.config.ts
  frontend/pages/admin/manage/groups/[id].vue
  frontend/pages/admin/manage/households/[id].vue
  frontend/pages/admin/manage/users/[id].vue
  frontend/pages/admin/manage/users/create.vue
  frontend/pages/admin/site-settings.vue
  frontend/pages/g/[groupSlug]/cookbooks/index.vue
  frontend/pages/g/[groupSlug]/r/create.vue
  frontend/pages/g/[groupSlug]/recipes/finder/index.vue
  frontend/pages/g/[groupSlug]/recipes/timeline.vue
  frontend/pages/group/data.vue
  frontend/pages/group/index.vue
  frontend/pages/group/migrations.vue
  frontend/pages/group/reports/[id].vue
  frontend/pages/household/index.vue
  frontend/pages/household/mealplan/settings.vue
  frontend/pages/household/members.vue
  frontend/pages/household/notifiers.vue
  frontend/pages/household/webhooks.vue
  frontend/pages/shopping-lists/[id].vue
  frontend/pages/shopping-lists/index.vue
  frontend/pages/user/profile/api-tokens.vue
  frontend/pages/user/profile/index.vue
Labels: bugfix

#6066 fix: Incorrect Usage of $vuetify.display
  frontend/components/Domain/Recipe/RecipeCardSection.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCardImage.vue
  frontend/components/Domain/Recipe/RecipeTimelineItem.vue
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/global/BaseStatCard.vue
  frontend/layouts/admin.vue
  frontend/pages/g/[groupSlug]/recipes/finder/index.vue
Labels: bugfix

#6075 fix: Optimize Recipe Favorites/Ratings
  frontend/components/Domain/Recipe/RecipeCard.vue
  frontend/components/Domain/Recipe/RecipeCardMobile.vue
  frontend/components/Domain/Recipe/RecipeCardRating.vue
  frontend/components/Domain/Recipe/RecipeFavoriteBadge.vue
  frontend/composables/api/api-client.ts
  frontend/composables/use-global-i18n.ts
  frontend/composables/use-users/user-ratings.ts
  frontend/layouts/admin.vue
  frontend/layouts/basic.vue
  frontend/layouts/blank.vue
  frontend/layouts/default.vue
  frontend/layouts/error.vue
Labels: bugfix

#6043 feat: consolidate settings gui
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/Layout/LayoutParts/AppSidebar.vue
  frontend/layouts/admin.vue
  frontend/lib/icons/icons.ts
  tests/e2e/login.spec.ts
Labels: feature

#6093 chore(l10n): New Crowdin updates
  frontend/lang/messages/ca-ES.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
Labels: l10n

#6105 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
Labels: l10n

#6108 fix: Context Menu Dialogs Not Working
  frontend/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenu.vue
  frontend/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenuContent.vue
Labels: bugfix

#6113 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
Labels: l10n

#6123 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/fr-FR.json
Labels: l10n

#6116 fix: Missing Locale Dates
  dev/code-generation/gen_ts_locales.py
  frontend/i18n.config.ts
Labels: bugfix

#6107 fix: Don't open the sidebar drawer by default on medium screens
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/Layout/LayoutParts/AppSidebar.vue
  frontend/layouts/admin.vue
Labels: bugfix

#6135 chore: Update GitHub Configs
  .github/workflows/locale-sync.yml
  .github/workflows/pull-request-lint.yml
Labels: chore

#6142 docs: fix typo starting-dev-server.md
  docs/docs/contributors/developers-guide/starting-dev-server.md
Labels: documentation

#6143 chore(l10n): New Crowdin updates
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/pt-BR.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
Labels: l10n

#6171 fix: Explorer Page State Not Working On Hitting Back
  frontend/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearch.vue
Labels: bugfix

#6145 chore(l10n): New Crowdin updates
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/he-IL.json
  mealie/lang/messages/bg-BG.json
  mealie/lang/messages/lt-LT.json
  mealie/repos/seed/resources/foods/locales/bg-BG.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/lt-LT.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/units/locales/bg-BG.json
  mealie/repos/seed/resources/units/locales/lt-LT.json
Labels: l10n

#6178 fix: Print Button Does Nothing
  frontend/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenu.vue
Labels: bugfix

#6141 feat: Manually calculate OpenAI Parsing Confidence
  mealie/schema/openai/recipe_ingredient.py
  mealie/services/parser_services/openai/parser.py
  tests/unit_tests/test_ingredient_parser.py
Labels: feature

#6194 fix: multiple RecipeRating backend calls
  frontend/components/Domain/Recipe/RecipeRating.vue
Labels: bugfix

#6198 docs: Add Info Regarding Theme Settings Config
  docs/docs/documentation/getting-started/faq.md
  docs/docs/documentation/getting-started/installation/backend-config.md
Labels: documentation

#6151 feat: Upgraded Ingredient Parsing Workflow
  docs/docs/documentation/community-guide/import-recipe-bookmarklet.md
  frontend/components/Domain/Recipe/RecipeIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue
  frontend/components/global/AppLogo.vue
  frontend/composables/recipe-page/shared-state.ts
  frontend/composables/use-new-recipe-options.ts
  frontend/composables/use-users/preferences.ts
  frontend/lang/messages/en-US.json
  frontend/lib/icons/icons.ts
  frontend/pages/g/[groupSlug]/r/[slug]/ingredient-parser.vue
  frontend/pages/g/[groupSlug]/r/create/html.vue
  frontend/pages/g/[groupSlug]/r/create/image.vue
  frontend/pages/g/[groupSlug]/r/create/url.vue
Labels: feature

#6176 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/uk-UA.json
  mealie/lang/messages/uk-UA.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
Labels: l10n

#6213 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n

#6215 fix: Actually Fix Token Time
  frontend/nuxt.config.ts
  frontend/plugins/axios.ts
  mealie/core/security/providers/auth_provider.py
  mealie/core/settings/settings.py
  mealie/routes/auth/auth.py
Labels: bugfix

#6223 docs: Fix formatting in some community guides
  docs/docs/documentation/community-guide/bring-api.md
  docs/docs/documentation/community-guide/home-assistant.md
  docs/docs/documentation/community-guide/ios-shortcut.md
  docs/docs/documentation/community-guide/swag.md
Labels: documentation

#6218 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/uk-UA.json
  mealie/lang/messages/nl-NL.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/pt-PT.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
Labels: l10n

#6231 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/lang/messages/fr-FR.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
Labels: l10n

#6236 fix: Remove constraint on unhashed password being 'LDAP'
  mealie/routes/users/crud.py
  mealie/services/user_services/password_reset_service.py
  tests/fixtures/fixture_users.py
Labels: bugfix

#6237 chore(l10n): New Crowdin updates
  frontend/lang/messages/pt-BR.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
Labels: l10n

#6243 feat: Simplify Default Layout Logic and Add Household.name To Cookbooks API
  docs/docs/overrides/api.html
  frontend/components/Layout/DefaultLayout.vue
  frontend/lib/api/types/cookbook.ts
  frontend/lib/api/types/openai.ts
  frontend/types/components.d.ts
  mealie/schema/cookbook/__init__.py
  mealie/schema/cookbook/cookbook.py
  tests/integration_tests/public_explorer_tests/test_public_cookbooks.py
  tests/integration_tests/user_household_tests/test_group_cookbooks.py
Labels: feature

#6253 fix: Make Ingredient Parser Dialog Use Full Space
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue
Labels: bugfix

#6254 chore(l10n): New Crowdin updates
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/ru-RU.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
Labels: l10n

#6240 chore: Upgrade Node and Nuxt
  .devcontainer/devcontainer.json
  .github/workflows/build-package.yml
  .github/workflows/e2e.yml
  .github/workflows/test-frontend.yml
  docker/Dockerfile
  docs/docs/contributors/developers-guide/starting-dev-server.md
  frontend/composables/api/use-app-info.ts
  frontend/eslint.config.mjs
  frontend/package.json
  frontend/pages/login.vue
  frontend/plugins/axios.ts
  frontend/yarn.lock
  tests/e2e/login.spec.ts
  tests/e2e/package.json
  tests/e2e/yarn.lock
Labels: chore

#6262 chore: Add Stricter Frontend Formatting
  .vscode/settings.json
  dev/code-generation/gen_py_pytest_data_paths.py
  dev/code-generation/gen_py_schema_exports.py
  dev/code-generation/gen_ts_types.py
  dev/code-generation/utils/template.py
  frontend/components/Domain/Cookbook/CookbookPage.vue
  frontend/components/Domain/Household/HouseholdPreferencesEditor.vue
  frontend/components/Domain/QueryFilterBuilder.vue
  frontend/components/Domain/Recipe/RecipeActionMenu.vue
  frontend/components/Domain/Recipe/RecipeCard.vue
  frontend/components/Domain/Recipe/RecipeCardMobile.vue
  frontend/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenuContent.vue
  frontend/components/Domain/Recipe/RecipeDataAliasManagerDialog.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageFooter.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCard.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue
  frontend/components/Domain/Recipe/RecipePrintView.vue
  frontend/components/Domain/Recipe/RecipeRating.vue
  frontend/components/Domain/ShoppingList/ShoppingListItemEditor.vue
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/Layout/LayoutParts/AppSidebar.vue
  frontend/components/global/AutoForm.vue
  frontend/components/global/BaseDialog.vue
  frontend/components/global/SafeMarkdown.vue
  frontend/composables/recipe-page/shared-state.ts
  frontend/composables/use-group-recipe-actions.ts
  frontend/composables/use-query-filter-builder.ts
  frontend/composables/use-shopping-list-item-actions.ts
  frontend/eslint.config.mjs
  frontend/layouts/error.vue
  frontend/lib/api/types/admin.ts
  frontend/lib/api/types/analytics.ts
  frontend/lib/api/types/cookbook.ts
  frontend/lib/api/types/household.ts
  frontend/lib/api/types/labels.ts
  frontend/lib/api/types/meal-plan.ts
  frontend/lib/api/types/non-generated.ts
  frontend/lib/api/types/reports.ts
  frontend/lib/api/types/response.ts
  frontend/lib/api/types/user.ts
  frontend/pages/admin/maintenance/index.vue
  frontend/pages/admin/setup.vue
  frontend/pages/g/[groupSlug]/r/create/bulk.vue
  frontend/pages/household/index.vue
  frontend/pages/household/mealplan/planner/edit.vue
  frontend/pages/household/mealplan/planner/view.vue
  frontend/pages/shopping-lists/index.vue
  frontend/pages/user/profile/api-tokens.vue
  frontend/types/auth.d.ts
Labels: chore

#6264 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
Labels: l10n

#6266 fix: Stores Not Populating Sometimes
  frontend/composables/partials/use-actions-factory.ts
  frontend/composables/partials/use-store-factory.ts
  frontend/composables/store/use-category-store.ts
  frontend/composables/store/use-cookbook-store.ts
  frontend/composables/store/use-food-store.ts
  frontend/composables/store/use-household-store.ts
  frontend/composables/store/use-label-store.ts
  frontend/composables/store/use-tag-store.ts
  frontend/composables/store/use-tool-store.ts
  frontend/composables/store/use-unit-store.ts
  frontend/composables/store/use-user-store.ts
  frontend/composables/use-group-recipe-actions.ts
  frontend/composables/use-utils.ts
Labels: bugfix

#6279 docs: Update TOKEN_TIME docs to include max
  docs/docs/documentation/getting-started/installation/backend-config.md
Labels: documentation

#6285 fix: Default to "0" qty when creating ingredients everywhere
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue
Labels: bugfix

#6286 fix: Restore recipe meta for non-logged-in users
  frontend/pages/g/[groupSlug]/r/[slug]/index.vue
  frontend/pages/g/[groupSlug]/shared/r/[id].vue
Labels: bugfix
