Repository mealie-recipes/mealie, pull requests merged in 2025-06, with the labels that each got.

#5507 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/nl-NL.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5537 fix: Fixing the OpenAPI Spec and the Call to delete a shared recipe.
  mealie/routes/shared/__init__.py
Labels: bugfix

#5512 fix: #5511, list item state doesn't change when offline
  frontend/composables/use-shopping-list-item-actions.ts
  frontend/package.json
  frontend/pages/shopping-lists/_id.vue
Labels: bugfix

#5552 fix: pwa not being installable after nuxt 3 upgrade
  frontend/components/Layout/DefaultLayout.vue
  frontend/layouts/basic.vue
  frontend/layouts/blank.vue
Labels: bugfix, build-image

#5553 fix: passwort strength indicator
  frontend/components/Domain/User/UserPasswordStrength.vue
  frontend/components/Domain/User/UserRegistrationForm.vue
  frontend/pages/user/profile/edit.vue
Labels: bugfix

#5560 fix: delete recipe instructions after nuxt 3 upgrade
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue
Labels: bugfix

#5577 fix: markdown list padding and replace nuxtjs/mdc
  frontend/components/global/SafeMarkdown.vue
  frontend/nuxt.config.ts
  frontend/package.json
  frontend/yarn.lock
Labels: bugfix

#5579 fix: recipe image creation
  frontend/pages/g/[groupSlug]/r/create/image.vue
  frontend/plugins/axios.ts
Labels: bugfix

#5558 docs: remove duplicate headline
  docs/docs/documentation/getting-started/installation/backend-config.md
Labels: documentation

#5588 fix: get recipe image by url
  frontend/components/Domain/Recipe/RecipeImageUploadBtn.vue
Labels: bugfix

#5592 docs: typo in app_settings_constructor docstring
  mealie/core/settings/settings.py
Labels: documentation

#5590 feat: create recipe from multiple images
  frontend/components/Layout/DefaultLayout.vue
  frontend/components/global/AppButtonUpload.vue
  frontend/composables/api/api-client.ts
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/non-generated.ts
  frontend/lib/api/user/recipes/recipe.ts
  frontend/pages/g/[groupSlug]/r/create.vue
  frontend/pages/g/[groupSlug]/r/create/image.vue
Labels: feature

#5603 fix: check for OPENAI_MODEL in OPENAI_FEATURE
  mealie/core/settings/settings.py
Labels: bugfix

#5609 fix: recipe page warnings
  frontend/components/Domain/Recipe/RecipeCard.vue
Labels: bugfix
