Repository mealie-recipes/mealie, pull requests merged in 2025-07, with the labels that each got.

#5633 fix: truncate slugs when too long
  mealie/repos/repository_recipes.py
  mealie/schema/recipe/recipe.py
  mealie/services/recipe/recipe_service.py
  tests/integration_tests/user_recipe_tests/test_recipe_crud.py
Labels: bugfix

#5630 chore: automatic crowdin sync via gh actions
  .github/workflows/locale-sync.yml
  Taskfile.yml
  dev/code-generation/gen_ts_locales.py
  dev/code-generation/main.py
  dev/code-generation/utils/template.py
Labels: chore

#5635 fix: load from env if available vs file
  dev/code-generation/gen_ts_locales.py
Labels: bugfix

#5636 fix: workflow permissions
  .github/workflows/locale-sync.yml
Labels: bugfix

#5627 fix: 500 error on recipe share link
  frontend/components/Domain/Recipe/RecipeAssets.vue
Labels: bugfix

#5641 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/sl-SI.json
Labels: l10n

#5644 fix: lint error from locale sync
  dev/code-generation/gen_ts_locales.py
  frontend/composables/use-locales/available-locales.ts
Labels: bugfix

#5643 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/he-IL.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5653 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/de-DE.json
Labels: l10n

#5656 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/de-DE.json
Labels: l10n

#5611 fix: Refactor Stores and Fix Missing Public Cookbooks
  frontend/components/Layout/DefaultLayout.vue
  frontend/composables/api/api-client.ts
  frontend/composables/store/use-category-store.ts
  frontend/composables/store/use-cookbook-store.ts
  frontend/composables/store/use-food-store.ts
  frontend/composables/store/use-household-store.ts
  frontend/composables/store/use-label-store.ts
  frontend/composables/store/use-tag-store.ts
  frontend/composables/store/use-tool-store.ts
  frontend/composables/store/use-unit-store.ts
  frontend/composables/store/use-user-store.ts
Labels: bugfix

#5659 fix: nutrition info visuals
  frontend/components/Domain/Recipe/RecipeNutrition.vue
Labels: bugfix

#5619 fix: Remove redundant get_one call in patch_one method
  mealie/services/recipe/recipe_service.py
Labels: bugfix

#5662 chore: Fix Dockerfile "AS" Case
  docker/Dockerfile
Labels: chore

#5664 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#5668 fix: Remove Padding On Print
  frontend/components/Domain/Recipe/RecipePrintContainer.vue
Labels: bugfix

#5682 chore(l10n): New Crowdin updates
  frontend/lang/messages/ru-RU.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
Labels: l10n

#5693 fix: set correct github tag in init py
  .github/workflows/release.yml
Labels: bugfix

#5701 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5699 fix: user & household creation
  frontend/composables/use-groups.ts
  frontend/composables/use-households.ts
  frontend/pages/admin/manage/households/index.vue
  frontend/pages/admin/manage/users/create.vue
Labels: bugfix

#5728 chore(l10n): New Crowdin updates
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/he-IL.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/labels/locales/he-IL.json
  mealie/repos/seed/resources/units/locales/sv-SE.json
Labels: l10n

#5725 fix: meal planner date range is correctly set
  frontend/pages/household/mealplan/planner.vue
Labels: bugfix

#5748 fix: Mealplan Regressions
  frontend/components/Domain/Recipe/RecipeContextMenu.vue
  frontend/pages/household/mealplan/planner.vue
Labels: bugfix

#5749 chore(l10n): New Crowdin updates
  mealie/lang/messages/fr-FR.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
Labels: l10n

#5754 fix: Patch XSS Vulnerability
  mealie/routes/spa/__init__.py
  tests/integration_tests/test_spa.py
Labels: bugfix

#5755 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5736 fix: style of recipe actions to be compliant with design schema
  frontend/components/Domain/Recipe/RecipeContextMenu.vue
  frontend/lib/icons/icons.ts
  frontend/pages/group/data/recipe-actions.vue
Labels: bugfix

#5764 chore(l10n): New Crowdin updates
  frontend/lang/messages/da-DK.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
Labels: l10n

#5770 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
Labels: l10n

#5775 chore(l10n): New Crowdin updates
  frontend/lang/messages/nl-NL.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
Labels: l10n

#5780 chore(l10n): New Crowdin updates
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/zh-TW.json
  mealie/repos/seed/resources/units/locales/zh-TW.json
Labels: l10n

#5787 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
Labels: l10n

#5792 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/units/locales/nl-NL.json
Labels: l10n

#5794 chore(l10n): New Crowdin updates
  frontend/lang/messages/zh-CN.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
Labels: l10n

#5737 fix: send the correct value for recipe scale and ensure the body is sent correctly
  frontend/composables/use-group-recipe-actions.ts
  frontend/lib/api/user/group-recipe-actions.ts
  mealie/routes/households/controller_group_recipe_actions.py
  mealie/schema/household/group_recipe_action.py
  tests/integration_tests/user_household_tests/test_group_recipe_actions.py
Labels: bugfix

#5798 fix: Better UX and Error Handling For Adding Timeline Events
  frontend/components/Domain/Recipe/RecipeLastMade.vue
  frontend/components/global/BaseDialog.vue
  frontend/lang/messages/en-US.json
Labels: bugfix

#5804 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
Labels: l10n

#5805 chore(l10n): New Crowdin updates
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/nl-NL.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#5809 chore(l10n): New Crowdin updates
  frontend/lang/messages/no-NO.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#5785 fix: add confirm button to bulk delete of tags
  frontend/pages/group/data/tags.vue
  frontend/pages/group/data/tools.vue
Labels: bugfix

#5817 chore(l10n): New Crowdin updates
  frontend/lang/messages/sv-SE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#5816 fix: Make Sure Test Webhook Always Fires
  frontend/composables/use-group-webhooks.ts
  mealie/routes/households/controller_webhooks.py
  mealie/services/event_bus_service/event_bus_listeners.py
  mealie/services/scheduler/tasks/post_webhooks.py
  tests/integration_tests/user_household_tests/test_group_webhooks.py
Labels: bugfix

#5811 fix: Optimize Recipe Timeline Requests
  frontend/components/Domain/Recipe/RecipeCardMobile.vue
  frontend/components/Domain/Recipe/RecipeTimeline.vue
  frontend/components/Domain/Recipe/RecipeTimelineItem.vue
  frontend/pages/g/[groupSlug]/recipes/timeline.vue
Labels: bugfix

#5739 fix: make only checkbox reactive
  frontend/components/Domain/ShoppingList/ShoppingListItem.vue
Labels: bugfix

#5828 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/el-GR.json
Labels: l10n

#5835 fix: remove v-lazy from RecipeCard
  frontend/components/Domain/Recipe/RecipeCard.vue
Labels: bugfix

#5837 fix: Delete Group From Admin Page
  frontend/composables/use-groups.ts
  frontend/pages/admin/manage/groups/index.vue
Labels: bugfix

#5829 fix: Nuxt 3 Ingredient Parsing Issues and Tooltip Positions
  frontend/components/Domain/Recipe/RecipeActionMenu.vue
  frontend/components/Domain/Recipe/RecipeAssets.vue
  frontend/components/Domain/Recipe/RecipeIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipeLastMade.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipeScaleEditButton.vue
  frontend/components/Domain/Recipe/RecipeTimelineBadge.vue
  frontend/components/Domain/ShoppingList/ShoppingListItem.vue
  frontend/components/Domain/User/UserAvatar.vue
  frontend/components/global/AppButtonCopy.vue
  frontend/components/global/BaseButtonGroup.vue
  frontend/lang/messages/en-US.json
  frontend/pages/admin/manage/groups/index.vue
  frontend/pages/admin/manage/households/index.vue
  frontend/pages/g/[groupSlug]/r/[slug]/ingredient-parser.vue
Labels: bugfix

#5854 chore(l10n): New Crowdin updates
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/hu-HU.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
Labels: l10n

#5855 chore(l10n): New Crowdin updates
  frontend/lang/messages/es-ES.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
Labels: l10n

#5860 fix: tags & tools edit confirm
  frontend/pages/group/data/tags.vue
  frontend/pages/group/data/tools.vue
Labels: bugfix

#5684 feat: Remove "Is Food" and "Disable Amounts" Flags
  dev/scripts/all_recipes_stress_test.py
  docs/docs/overrides/api.html
  frontend/components/Domain/Household/HouseholdPreferencesEditor.vue
  frontend/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue
  frontend/components/Domain/Recipe/RecipeIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipeIngredientListItem.vue
  frontend/components/Domain/Recipe/RecipeIngredients.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientToolsView.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageScale.vue
  frontend/components/Domain/Recipe/RecipePrintView.vue
  frontend/components/Domain/Recipe/RecipeSettingsSwitches.vue
  frontend/components/Domain/ShoppingList/ShoppingListItem.vue
  frontend/components/Domain/ShoppingList/ShoppingListItemEditor.vue
  frontend/composables/recipe-page/use-extract-ingredient-references.ts
  frontend/composables/recipes/use-recipe-ingredients.test.ts
  frontend/composables/recipes/use-recipe-ingredients.ts
  frontend/lang/messages/en-US.json
  frontend/lib/api/types/household.ts
  frontend/lib/api/types/recipe.ts
  frontend/pages/g/[groupSlug]/r/[slug]/ingredient-parser.vue
  frontend/pages/group/data/recipes.vue
  frontend/pages/household/index.vue
  frontend/pages/shopping-lists/[id].vue
  mealie/alembic/versions/2025-07-11-20.17.10_d7b3ce6fa31a_empty_migration_to_fix_food_flag_data.py
  mealie/db/models/household/preferences.py
  mealie/db/models/household/shopping_list.py
  mealie/db/models/recipe/settings.py
  mealie/repos/repository_recipes.py
  mealie/routes/spa/__init__.py
  mealie/schema/household/group_shopping_list.py
  mealie/schema/household/household_preferences.py
  mealie/schema/recipe/recipe.py
  mealie/schema/recipe/recipe_ingredient.py
  mealie/schema/recipe/recipe_settings.py
  mealie/services/household_services/shopping_lists.py
  mealie/services/migrations/_migration_base.py
  mealie/services/parser_services/ingredient_parser.py
  mealie/services/recipe/recipe_service.py
  mealie/services/user_services/registration_service.py
  tests/fixtures/fixture_recipe.py
  tests/fixtures/fixture_shopping_lists.py
  tests/integration_tests/admin_tests/test_admin_household_actions.py
  tests/integration_tests/public_explorer_tests/test_public_recipes.py
  tests/integration_tests/user_recipe_tests/test_recipe_ingredients.py
  tests/integration_tests/user_recipe_tests/test_recipe_suggestions.py
  tests/unit_tests/schema_tests/test_shopping_list_ingredient.py
Labels: feature
