Repository mealie-recipes/mealie, pull requests merged in 2025-03, with the labels that each got.

#5142 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/units/locales/gl-ES.json
Labels: l10n

#5145 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
Labels: l10n

#5149 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
  mealie/lang/messages/gl-ES.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
Labels: l10n

#5166 dev: chown commandhistory to correct user during devcontainer creation
  .devcontainer/devcontainer.json
Labels: dev

#5161 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
  mealie/lang/messages/gl-ES.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/units/locales/gl-ES.json
Labels: l10n

#5174 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/gl-ES.json
Labels: l10n

#5175 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/gl-ES.json
Labels: l10n

#5176 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
Labels: l10n

#5179 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/zh-CN.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/labels/locales/gl-ES.json
Labels: l10n

#5199 docs: Re-add missing environment variable documentation
  docs/docs/documentation/getting-started/installation/backend-config.md
Labels: documentation

#5162 fix: Case Insensitive Query Filters
  mealie/schema/response/query_filter.py
  tests/unit_tests/repository_tests/test_pagination.py
Labels: bugfix

#5201 docs: faq.md: fix paths to scripts
  docs/docs/documentation/getting-started/faq.md
Labels: documentation

#5189 feat: Update seeding to use new foods list format - round 2
  dev/scripts/convert_seed_files_to_new_format.py
  frontend/lang/messages/en-US.json
  mealie/repos/seed/resources/foods/locales/af-ZA.json
  mealie/repos/seed/resources/foods/locales/ar-SA.json
  mealie/repos/seed/resources/foods/locales/bg-BG.json
  mealie/repos/seed/resources/foods/locales/ca-ES.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/en-US.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fi-FI.json
  mealie/repos/seed/resources/foods/locales/fr-BE.json
  mealie/repos/seed/resources/foods/locales/fr-CA.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/hr-HR.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/is-IS.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
  mealie/repos/seed/resources/foods/locales/ko-KR.json
  mealie/repos/seed/resources/foods/locales/lt-LT.json
  mealie/repos/seed/resources/foods/locales/lv-LV.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/foods/locales/pt-PT.json
  mealie/repos/seed/resources/foods/locales/ro-RO.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
  mealie/repos/seed/resources/foods/locales/sl-SI.json
  mealie/repos/seed/resources/foods/locales/sr-SP.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/foods/locales/tr-TR.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
  mealie/repos/seed/resources/foods/locales/vi-VN.json
  mealie/repos/seed/resources/foods/locales/zh-CN.json
  mealie/repos/seed/resources/foods/locales/zh-TW.json
  mealie/repos/seed/seeders.py
  tests/integration_tests/user_group_tests/test_group_seeder.py
  tests/integration_tests/user_household_tests/test_shopping_list_labels.py
Labels: feature

#5208 fix: Revert "feat: Update seeding to use new foods list format - round 2"
  dev/scripts/convert_seed_files_to_new_format.py
  frontend/lang/messages/en-US.json
  mealie/repos/seed/resources/foods/locales/af-ZA.json
  mealie/repos/seed/resources/foods/locales/ar-SA.json
  mealie/repos/seed/resources/foods/locales/bg-BG.json
  mealie/repos/seed/resources/foods/locales/ca-ES.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/en-US.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fi-FI.json
  mealie/repos/seed/resources/foods/locales/fr-BE.json
  mealie/repos/seed/resources/foods/locales/fr-CA.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/hr-HR.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/is-IS.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
  mealie/repos/seed/resources/foods/locales/ko-KR.json
  mealie/repos/seed/resources/foods/locales/lt-LT.json
  mealie/repos/seed/resources/foods/locales/lv-LV.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/foods/locales/pt-PT.json
  mealie/repos/seed/resources/foods/locales/ro-RO.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
  mealie/repos/seed/resources/foods/locales/sl-SI.json
  mealie/repos/seed/resources/foods/locales/sr-SP.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/foods/locales/tr-TR.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
  mealie/repos/seed/resources/foods/locales/vi-VN.json
  mealie/repos/seed/resources/foods/locales/zh-CN.json
  mealie/repos/seed/resources/foods/locales/zh-TW.json
  mealie/repos/seed/seeders.py
  tests/integration_tests/user_group_tests/test_group_seeder.py
  tests/integration_tests/user_household_tests/test_shopping_list_labels.py
Labels: feature

#5228 feat: OIDC: Call userinfo if no claims found in id token
  mealie/core/exceptions.py
  mealie/core/security/providers/openid_provider.py
  mealie/routes/auth/auth.py
  tests/unit_tests/core/security/providers/test_openid_provider.py
Labels: feature

#5233 chore: Bump Ruff to 0.11.0
  mealie/schema/_mealie/datetime_parse.py
  poetry.lock
  pyproject.toml
Labels: chore

#5154 fix: "NOT IN" doesn't apply filter properly
  mealie/schema/response/query_filter.py
  tests/unit_tests/repository_tests/test_pagination.py
Labels: bugfix

#5244 fix: spelling of GitHub
  frontend/lang/messages/en-US.json
Labels: bugfix

#5245 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
Labels: l10n

#5246 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5248 chore(l10n): New Crowdin updates
  frontend/lang/messages/nl-NL.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5250 chore(l10n): New Crowdin updates
  frontend/lang/messages/es-ES.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
Labels: l10n

#5252 chore(l10n): New Crowdin updates
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/gl-ES.json
  mealie/lang/messages/en-GB.json
  mealie/repos/seed/resources/foods/locales/bg-BG.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
Labels: l10n

#5263 fix: update admin scripts paths in docs
  docs/docs/documentation/getting-started/faq.md
Labels: bugfix

#5280 fix: remove unmaintained ios shortcut
  docs/docs/documentation/community-guide/ios.md
  docs/docs/overrides/api.html
Labels: bugfix

#5262 chore(l10n): New Crowdin updates
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/no-NO.json
  mealie/lang/messages/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/units/locales/pt-BR.json
Labels: l10n

#5290 fix: Pre-download NLTK during Docker build
  docker/Dockerfile
Labels: bugfix

#5235 dev: add pull request image build workflow
  .github/workflows/build-package.yml
  .github/workflows/e2e.yml
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
  .github/workflows/pull-requests.yml
  .github/workflows/release.yml
  .github/workflows/test-backend.yml
  .github/workflows/test-frontend.yml
Labels: dev, build-image

#5281 chore(l10n): New Crowdin updates
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/no-NO.json
  mealie/lang/messages/no-NO.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
Labels: l10n
