Repository mealie-recipes/mealie, pull requests merged in 2025-02, with the labels that each got.

#4812 feat: Add new labels and foods for en-US language. Update all locale seeding files and seeding logic to parse the new format Only add new labels, units, and foods during seeding (checking against existing names)
  dev/scripts/convert_seed_files_to_new_format.py
  frontend/lang/messages/en-US.json
  mealie/repos/seed/resources/foods/locales/af-ZA.json
  mealie/repos/seed/resources/foods/locales/ar-SA.json
  mealie/repos/seed/resources/foods/locales/bg-BG.json
  mealie/repos/seed/resources/foods/locales/ca-ES.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/de-DE.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/en-GB.json
  mealie/repos/seed/resources/foods/locales/en-US.json
  mealie/repos/seed/resources/foods/locales/es-ES.json
  mealie/repos/seed/resources/foods/locales/fi-FI.json
  mealie/repos/seed/resources/foods/locales/fr-BE.json
  mealie/repos/seed/resources/foods/locales/fr-CA.json
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/foods/locales/he-IL.json
  mealie/repos/seed/resources/foods/locales/hr-HR.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/is-IS.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/ja-JP.json
  mealie/repos/seed/resources/foods/locales/ko-KR.json
  mealie/repos/seed/resources/foods/locales/lt-LT.json
  mealie/repos/seed/resources/foods/locales/lv-LV.json
  mealie/repos/seed/resources/foods/locales/nl-NL.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/foods/locales/pl-PL.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/foods/locales/pt-PT.json
  mealie/repos/seed/resources/foods/locales/ro-RO.json
  mealie/repos/seed/resources/foods/locales/ru-RU.json
  mealie/repos/seed/resources/foods/locales/sk-SK.json
  mealie/repos/seed/resources/foods/locales/sl-SI.json
  mealie/repos/seed/resources/foods/locales/sr-SP.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/foods/locales/tr-TR.json
  mealie/repos/seed/resources/foods/locales/uk-UA.json
  mealie/repos/seed/resources/foods/locales/vi-VN.json
  mealie/repos/seed/resources/foods/locales/zh-CN.json
  mealie/repos/seed/resources/foods/locales/zh-TW.json
  mealie/repos/seed/seeders.py
  tests/integration_tests/user_group_tests/test_group_seeder.py
  tests/integration_tests/user_household_tests/test_shopping_list_labels.py
Labels: feature

#5016 chore(l10n): New Crowdin updates
  frontend/lang/messages/fi-FI.json
  mealie/lang/messages/fi-FI.json
  mealie/lang/messages/fr-BE.json
  mealie/lang/messages/fr-CA.json
  mealie/repos/seed/resources/foods/locales/el-GR.json
  mealie/repos/seed/resources/foods/locales/fi-FI.json
  mealie/repos/seed/resources/foods/locales/fr-CA.json
  mealie/repos/seed/resources/labels/locales/fi-FI.json
  mealie/repos/seed/resources/units/locales/fi-FI.json
Labels: l10n

#5018 chore(l10n): New Crowdin updates
  frontend/lang/messages/it-IT.json
Labels: l10n

#5021 chore(l10n): New Crowdin updates
  frontend/lang/messages/pt-BR.json
  mealie/lang/messages/pt-BR.json
  mealie/repos/seed/resources/foods/locales/pt-BR.json
  mealie/repos/seed/resources/units/locales/pt-BR.json
Labels: l10n

#5032 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/pt-PT.json
Labels: l10n

#5039 chore: Remove Warnings
  mealie/app.py
  poetry.lock
Labels: chore

#5046 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/sl-SI.json
Labels: l10n

#5045 fix: Shorten Indexes
  .vscode/settings.json
  mealie/alembic/versions/2025-02-09-15.31.00_7cf3054cbbcc_remove_instructions_index.py
  mealie/db/models/_model_base.py
  mealie/db/models/recipe/instruction.py
Labels: bugfix

#4958 feat: support `_FILE` suffix for docker secrets (again)
  docker/entry.sh
  docs/docs/documentation/getting-started/installation/backend-config.md
Labels: feature

#5073 chore(l10n): New Crowdin updates
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/sv-SE.json
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/labels/locales/sv-SE.json
Labels: l10n

#5080 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/fr-FR.json
  mealie/repos/seed/resources/units/locales/fr-FR.json
Labels: l10n

#5093 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/sv-SE.json
  mealie/repos/seed/resources/units/locales/sv-SE.json
Labels: l10n

#5038 fix: Only run migration data fixes on migrations
  mealie/db/init_db.py
Labels: bugfix

#5098 chore(l10n): New Crowdin updates
  frontend/lang/messages/uk-UA.json
Labels: l10n

#5099 chore(l10n): New Crowdin updates
  frontend/lang/messages/uk-UA.json
  mealie/lang/messages/uk-UA.json
  mealie/repos/seed/resources/units/locales/uk-UA.json
Labels: l10n

#5100 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
Labels: l10n

#5101 chore(l10n): New Crowdin updates
  frontend/lang/messages/gl-ES.json
  mealie/lang/messages/gl-ES.json
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/units/locales/gl-ES.json
Labels: l10n

#5102 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/gl-ES.json
  mealie/repos/seed/resources/units/locales/gl-ES.json
Labels: l10n

#4843 docs: Add additional information and tips to Backup & Restore Usage Documentation Page & Shopping List
  docs/docs/documentation/getting-started/features.md
  docs/docs/documentation/getting-started/usage/backups-and-restoring.md
Labels: documentation

#5065 fix: Invalidate Expired Shared Links
  mealie/app.py
  mealie/routes/recipe/shared_routes.py
  mealie/routes/shared/__init__.py
  mealie/schema/recipe/recipe_share_token.py
  mealie/services/scheduler/tasks/__init__.py
  mealie/services/scheduler/tasks/purge_expired_share_tokens.py
  tests/integration_tests/user_recipe_tests/test_recipe_share_tokens.py
  tests/unit_tests/services_tests/scheduler/tasks/test_purge_expired_share_tokens.py
Labels: bugfix

#5026 feat: redesign recipe info card
  frontend/components/Domain/Recipe/RecipeLastMade.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCard.vue
  frontend/components/Domain/Recipe/RecipePrintView.vue
  frontend/components/Domain/Recipe/RecipeTimeCard.vue
  frontend/components/Domain/Recipe/RecipeYield.vue
  frontend/lang/messages/en-US.json
  frontend/lib/icons/icons.ts
Labels: feature

#5105 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
Labels: l10n

#5106 chore(l10n): New Crowdin updates
  mealie/lang/messages/fr-CA.json
Labels: l10n

#5054 fix: Bulk Add Recipes to Shopping List
  frontend/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue
  frontend/lib/api/types/household.ts
  frontend/lib/api/types/recipe.ts
  frontend/lib/api/user/group-shopping-lists.ts
  frontend/pages/shopping-lists/_id.vue
  mealie/routes/households/controller_shopping_lists.py
  mealie/schema/household/__init__.py
  mealie/schema/household/group_shopping_list.py
  mealie/services/household_services/shopping_lists.py
  tests/fixtures/fixture_recipe.py
  tests/integration_tests/user_household_tests/test_group_shopping_list_items.py
  tests/integration_tests/user_household_tests/test_group_shopping_lists.py
  tests/utils/api_routes/__init__.py
Labels: bugfix

#5115 fix: Remove `br` encoding from scraper
  mealie/services/scraper/user_agents_manager.py
Labels: bugfix

#5131 chore(l10n): New Crowdin updates
  frontend/lang/messages/da-DK.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
Labels: l10n

#5134 chore: Renovate Ignore Python Upgrades
  renovate.json
Labels: chore

#5135 chore(l10n): New Crowdin updates
  frontend/lang/messages/af-ZA.json
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/bg-BG.json
  frontend/lang/messages/ca-ES.json
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/de-DE.json
  frontend/lang/messages/el-GR.json
  frontend/lang/messages/en-GB.json
  frontend/lang/messages/es-ES.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/fr-BE.json
  frontend/lang/messages/fr-CA.json
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/gl-ES.json
  frontend/lang/messages/he-IL.json
  frontend/lang/messages/hr-HR.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/is-IS.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ja-JP.json
  frontend/lang/messages/ko-KR.json
  frontend/lang/messages/lt-LT.json
  frontend/lang/messages/lv-LV.json
  frontend/lang/messages/nl-NL.json
  frontend/lang/messages/no-NO.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/pt-BR.json
  frontend/lang/messages/pt-PT.json
  frontend/lang/messages/ro-RO.json
  frontend/lang/messages/ru-RU.json
  frontend/lang/messages/sk-SK.json
  frontend/lang/messages/sl-SI.json
  frontend/lang/messages/sr-SP.json
  frontend/lang/messages/sv-SE.json
  frontend/lang/messages/tr-TR.json
  frontend/lang/messages/uk-UA.json
  frontend/lang/messages/vi-VN.json
  frontend/lang/messages/zh-CN.json
  frontend/lang/messages/zh-TW.json
Labels: l10n
