Repository mealie-recipes/mealie, pull requests merged in 2025-01, with the labels that each got.

#4815 chore(l10n): New Crowdin updates
  frontend/lang/messages/cs-CZ.json
  frontend/lang/messages/pl-PL.json
Labels: l10n

#4821 chore(l10n): New Crowdin updates
  frontend/lang/messages/pl-PL.json
Labels: l10n

#4827 chore(l10n): New Crowdin updates
  mealie/repos/seed/resources/foods/locales/sv-SE.json
Labels: l10n

#4831 chore(l10n): New Crowdin updates
  frontend/lang/messages/fr-FR.json
  frontend/lang/messages/it-IT.json
  mealie/lang/messages/it-IT.json
  mealie/lang/messages/tr-TR.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/units/locales/no-NO.json
  mealie/repos/seed/resources/units/locales/tr-TR.json
Labels: l10n

#4837 fix: Autocomplete Accessibility on Login form
  frontend/pages/login.vue
Labels: bugfix

#4835 fix: RecipeActionMenu location
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageHeader.vue
Labels: bugfix

#4840 chore(l10n): New Crowdin updates
  frontend/lang/messages/ro-RO.json
Labels: l10n

#4852 chore(l10n): New Crowdin updates
  frontend/lang/messages/pt-PT.json
  mealie/lang/messages/pt-PT.json
  mealie/lang/messages/sv-SE.json
Labels: l10n

#4849 fix: remove edit scale icon when not scalable
  frontend/components/Domain/Recipe/RecipeScaleEditButton.vue
Labels: bugfix

#4853 feat: add make_admin script
  docs/docs/documentation/getting-started/faq.md
  docs/docs/overrides/api.html
  mealie/scripts/make_admin.py
Labels: feature

#4857 fix: remove kitchen timer
  frontend/assets/audio/kitchen_alarm.mp3
  frontend/components/Domain/Recipe/RecipeActionMenu.vue
  frontend/components/Domain/Recipe/RecipeTimerMenu.vue
  frontend/lang/messages/en-US.json
  frontend/lib/icons/icons.ts
  frontend/nuxt.config.js
Labels: bugfix

#4869 chore(l10n): New Crowdin updates
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/it-IT.json
  frontend/lang/messages/ro-RO.json
  mealie/lang/messages/hu-HU.json
  mealie/lang/messages/ro-RO.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/foods/locales/it-IT.json
  mealie/repos/seed/resources/foods/locales/ro-RO.json
  mealie/repos/seed/resources/units/locales/ro-RO.json
Labels: l10n

#4875 chore(l10n): New Crowdin updates
  frontend/lang/messages/da-DK.json
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/hu-HU.json
  frontend/lang/messages/ro-RO.json
  mealie/lang/messages/da-DK.json
  mealie/lang/messages/hu-HU.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/foods/locales/hu-HU.json
  mealie/repos/seed/resources/units/locales/da-DK.json
Labels: l10n

#4877 chore(l10n): New Crowdin updates
  frontend/lang/messages/et-EE.json
  frontend/lang/messages/pl-PL.json
  frontend/lang/messages/ro-RO.json
Labels: l10n

#4882 chore(l10n): New Crowdin updates
  frontend/lang/messages/ar-SA.json
  mealie/lang/messages/ar-SA.json
  mealie/repos/seed/resources/labels/locales/ar-SA.json
  mealie/repos/seed/resources/units/locales/ar-SA.json
Labels: l10n

#4887 docs: Update FAQ to include Nutritional Values and enabling per recipe / household
  docs/docs/documentation/getting-started/faq.md
Labels: documentation

#4888 docs: Fix Spelling Errors on Nutritional Values
  docs/docs/documentation/getting-started/faq.md
Labels: documentation

#4616 feat: Move "on hand" and "last made" to household
  docs/docs/overrides/api.html
  frontend/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue
  frontend/components/Domain/Recipe/RecipeLastMade.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCard.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientToolsView.vue
  frontend/components/global/AppLoader.vue
  frontend/composables/recipes/use-recipe-tools.ts
  frontend/composables/store/use-food-store.ts
  frontend/composables/store/use-tool-store.ts
  frontend/lib/api/types/admin.ts
  frontend/lib/api/types/cookbook.ts
  frontend/lib/api/types/household.ts
  frontend/lib/api/types/meal-plan.ts
  frontend/lib/api/types/recipe.ts
  frontend/lib/api/user/households.ts
  frontend/pages/g/_groupSlug/recipes/tools/index.vue
  frontend/pages/group/data/foods.vue
  frontend/pages/group/data/recipe-actions.vue
  frontend/pages/group/data/tools.vue
  mealie/alembic/versions/2024-11-20-17.30.41_b9e516e2d3b3_add_household_to_recipe_last_made_.py
  mealie/db/models/household/__init__.py
  mealie/db/models/household/household.py
  mealie/db/models/household/household_to_recipe.py
  mealie/db/models/recipe/ingredient.py
  mealie/db/models/recipe/recipe.py
  mealie/db/models/recipe/tool.py
  mealie/repos/repository_factory.py
  mealie/repos/repository_generic.py
  mealie/repos/repository_household.py
  mealie/repos/repository_recipes.py
  mealie/routes/households/controller_household_self_service.py
  mealie/routes/households/controller_mealplan.py
  mealie/routes/organizers/controller_tools.py
  mealie/routes/recipe/recipe_crud_routes.py
  mealie/routes/unit_and_foods/foods.py
  mealie/schema/household/__init__.py
  mealie/schema/household/household.py
  mealie/schema/recipe/recipe.py
  mealie/schema/recipe/recipe_ingredient.py
  mealie/schema/recipe/recipe_tool.py
  mealie/schema/response/query_filter.py
  mealie/services/household_services/household_service.py
  mealie/services/recipe/recipe_service.py
  mealie/services/scheduler/tasks/create_timeline_events.py
  pyproject.toml
  tests/integration_tests/user_household_tests/test_household_self_service.py
  tests/integration_tests/user_recipe_tests/test_recipe_cross_household.py
  tests/integration_tests/user_recipe_tests/test_recipe_suggestions.py
  tests/unit_tests/repository_tests/test_pagination.py
  tests/unit_tests/repository_tests/test_recipe_repository.py
  tests/unit_tests/services_tests/backup_v2_tests/test_backup_v2.py
  tests/unit_tests/services_tests/scheduler/tasks/test_create_timeline_events.py
  tests/utils/api_routes/__init__.py
Labels: feature

#4803 fix: Preserve orientation when converting to .webp
  mealie/pkgs/img/minify.py
Labels: bugfix

#4896 chore(l10n): New Crowdin updates
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/et-EE.json
  mealie/lang/messages/et-EE.json
  mealie/repos/seed/resources/foods/locales/et-EE.json
Labels: l10n

#4726 fix: Recipe comments display a username/id rather than …
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageComments.vue
  mealie/schema/recipe/recipe_comments.py
  tests/fixtures/fixture_admin.py
  tests/fixtures/fixture_users.py
  tests/integration_tests/user_recipe_tests/test_recipe_comments.py
  tests/utils/fixture_schemas.py
Labels: bugfix

#4810 fix: Refresh recipe section when clicking card tag chip
  frontend/components/Domain/Recipe/RecipeCard.vue
  frontend/components/Domain/Recipe/RecipeCardMobile.vue
  frontend/components/Domain/Recipe/RecipeCardSection.vue
  frontend/components/Domain/Recipe/RecipeChips.vue
  frontend/components/Domain/Recipe/RecipeDataTable.vue
  frontend/components/Domain/Recipe/RecipeExplorerPage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
  frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageOrganizers.vue
Labels: bugfix

#4899 docs: remove titles from within individual FAQs
  docs/docs/documentation/getting-started/faq.md
Labels: documentation

#4900 chore(l10n): New Crowdin updates
  frontend/lang/messages/ar-SA.json
  frontend/lang/messages/no-NO.json
  mealie/lang/messages/no-NO.json
  mealie/repos/seed/resources/foods/locales/ar-SA.json
  mealie/repos/seed/resources/foods/locales/et-EE.json
  mealie/repos/seed/resources/foods/locales/no-NO.json
  mealie/repos/seed/resources/labels/locales/et-EE.json
  mealie/repos/seed/resources/units/locales/et-EE.json
Labels: l10n

#4902 fix: PWA - Allow CORS and add UseCredentials to nuxt.config.js
  frontend/nuxt.config.js
Labels: bugfix

#4906 chore(l10n): New Crowdin updates
  frontend/lang/messages/cs-CZ.json
  mealie/lang/messages/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/ar-SA.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/units/locales/cs-CZ.json
Labels: l10n

#4897 docs: Add to FAQ: When / how to use Linked Ingredients
  docs/docs/documentation/getting-started/faq.md
Labels: documentation

#4920 docs: Add community guide for integrating the Mealie-Bring-API
  docs/docs/documentation/community-guide/bring-api.md
Labels: documentation

#4929 fix: prevent recipe sharing from different group
  mealie/routes/shared/__init__.py
  tests/integration_tests/user_recipe_tests/test_recipe_share_tokens.py
Labels: bugfix

#4934 chore(l10n): New Crowdin updates
  frontend/lang/messages/cs-CZ.json
  mealie/repos/seed/resources/foods/locales/cs-CZ.json
  mealie/repos/seed/resources/units/locales/cs-CZ.json
Labels: l10n

#4938 chore(l10n): New Crowdin updates
  mealie/lang/messages/da-DK.json
  mealie/repos/seed/resources/foods/locales/da-DK.json
  mealie/repos/seed/resources/units/locales/da-DK.json
Labels: l10n

#4942 docs: update oidcv2 authelia link
  docs/docs/documentation/getting-started/authentication/oidc-v2.md
Labels: documentation

#4415 feat: Shopping list UI overhaul - three dot menu
  frontend/pages/shopping-lists/_id.vue
  frontend/pages/shopping-lists/index.vue
Labels: feature

#4953 chore(l10n): New Crowdin updates
  frontend/lang/messages/el-GR.json
Labels: l10n

#4952 feat: Add Servings/Yield to Recipe Actions
  docs/docs/documentation/getting-started/features.md
  frontend/components/Domain/Recipe/RecipeContextMenu.vue
  frontend/composables/use-group-recipe-actions.ts
Labels: feature

#4948 fix: Ensure bring api docs are shown (PR 4920)
  docs/mkdocs.yml
Labels: bugfix

#4985 fix: Remove API Tokens from User APIs
  frontend/lib/api/types/user.ts
  mealie/routes/users/api_tokens.py
  mealie/schema/user/__init__.py
  mealie/schema/user/user.py
  tests/integration_tests/user_tests/test_user_api_token.py
Labels: bugfix

#4980 fix: Fixed LastMade recipes sorting order
  frontend/components/Domain/Recipe/RecipeCardSection.vue
  frontend/composables/recipes/use-recipes.ts
  frontend/lib/api/user/recipes/recipe.ts
Labels: bugfix

#4991 chore(l10n): New Crowdin updates
  frontend/lang/messages/fi-FI.json
  frontend/lang/messages/lt-LT.json
  mealie/lang/messages/lt-LT.json
  mealie/repos/seed/resources/foods/locales/fi-FI.json
  mealie/repos/seed/resources/units/locales/fi-FI.json
  mealie/repos/seed/resources/units/locales/lt-LT.json
Labels: l10n
